### ISSUE TITLE
feat: support optional const / new

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#1313] opened 2018-05-11 22:36 UTC
This is a status tracking issue that we'll be referring to in the Angular 5 docs. Specifically, we'll be warning readers that Angular 5 does not yet support optional const/new in a banner at the top.

cc @kevmoo @kwalrath

**Comment by kevmoo** [comment] 2018-05-11 22:39
I think landing the new analyzer should get us a lot closer here - https://dart-review.googlesource.com/c/sdk/+/54741

...I *think*

**Comment by matanlurey** [comment] 2018-05-11 22:45
We are using a much older analyzer frontend (`AnalysisContext`). I have no idea if it will work. The last time we tested (not too long ago) it caused unexpected issues with the compiler (types not showing up properly, etc).

**Comment by kevmoo** [comment] 2018-05-11 22:52
Right...

**Comment by chalin** [comment] 2018-05-24 11:27
@matanlurey - https://github.com/dart-lang/site-webdev/issues/1611 seems to suggest that Angular supports omitting `new`. Is that the case? (If so, we can refocus this issue to be about optional `const` only.)

**Comment by chalin** [comment] 2018-05-24 19:26
As reported at https://github.com/dart-lang/site-webdev/pull/1614#issuecomment-391818316, for all Angular example apps, after stripping out all `new` keywords from Dart sources:

> All E2E and component tests pass under ddc and dart2js.

**Comment by chalin** [comment] 2018-05-24 19:31
Btw, the component tests are using the new pageloader.

**Comment by matanlurey** [comment] 2018-05-30 02:42
I saw this comment on the `dart-lang/build` gitter:

> > Source_gen problem...
> This work as expected:
> 
> ```
> @Propagate(const ['id', 'name', 'enabled', 'sex'], const {
>     'items': const Propagate(['id', 'type', 'index', 'insertType.id',
>     'insertType.name', 'video.id', 'video.name'])
>   })
> ```
> Becomes this ```DartObject```
> ```
> Propagate (fields = List ([String ('id'), String ('name'), String ('enabled'), String ('sex')]); relationships = Map ({String ('items') = Propagate (fields = List ([String ('id'), String ('type'), String ('index'), String ('insertType.id'), String ('insertType.name'), String ('video.id'), String ('video.name')]); relationships = Null (null); when = Null (null))}); when = Null (null))
> ```
> 
> When I remove the *const* keyword from the *relationships* property 
> ```
> const {
>     'items': ...
> ```
> 
> It becomes this ```DartObject```: 
> 
> ```
> Propagate (fields = List ([String ('id'), String ('name'), String ('enabled'), String ('sex')]); relationships = Null (null); when = Null (null))
> ```
> 
> The relatshionps property becomes null 
> 

/cc @MichaelRFairhurst @natebosch

**Comment by MichaelRFairhurst** [comment] 2018-05-30 18:17
Looks like @scheglov may have independently solved this: https://dart-review.googlesource.com/c/sdk/+/57000

I can confirm what @rkj ran into was fixed by this. I can keep testing other cases to see if they were the same issue.

**Comment by alorenzen** [comment] 2018-06-14 21:02
At this point, we think that we are good to go here. We're going to remove new/const from our examples and confirm they still work before closing this issue.

**Comment by matanlurey** [comment] 2018-06-14 21:04
@alorenzen Want to send a CL internally removing it?

**Comment by alorenzen** [comment] 2018-06-14 21:04
That's my plan for the afternoon

**Comment by chalin** [comment] 2018-06-19 12:43
All done? Can this be closed?

**Comment by matanlurey** [comment] 2018-06-27 00:10
Yes.

**Closed by matanlurey** 2018-06-27 00:10 UTC
Labels: ✉ dependency: build, ✏ documentation
