### ISSUE TITLE
Parent route not shown as active when child route is active

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#1253] opened 2018-04-17 11:38 UTC
Try this:

- Visit the **Crisis Center of the Router example app:** https://webdev-dartlang-org-dev.firebaseapp.com/examples/router/#crises
- Note that the _Crisis Center_ tab is shown as active. The tab's style is set via **routerLinkActive**.
- Select a crisis, or visit https://webdev-dartlang-org-dev.firebaseapp.com/examples/router/#crises/4
- Note how the _Crisis Center_ tab is no longer active.

The crisis-detail is a child route of the parent crisis-center route, so I'd expect the parent route to still be considered active. I guess that depends if **routerLinkActive** matches the current path using equals or startsWith.

FYI, in the [Angular TS Router app](https://angular.io/generated/live-examples/router/stackblitz.html), the _Crisis Center_ tab is shown as active even when the child route is the current one: https://gaamqgoddpj.angular.stackblitz.io/crisis-center/4

From the [Angular TS Router docs](https://angular.io/guide/router#routerlinkactive-binding):

> The RouterLinkActive directive toggles css classes for active RouterLinks based on the current RouterState. This cascades down through each level of the route tree, so parent and child router links can be active at the same time. To override this behavior, you can bind to the [routerLinkActiveOptions] input binding with the { exact: true } expression. By using { exact: true }, a given RouterLink will only be active if its URL is an exact match to the current URL.

Repro and environment:

- Angular router sources: https://github.com/angular-examples/router
- Dart 2-dev.48
- Angular 5-alpha+10, etc.

cc @kwalrath

**Comment by leonsenft** [comment] 2018-04-17 23:07
Duplicate of https://github.com/dart-lang/angular/issues/737. Thanks for filing with these details though!

**Closed by leonsenft** 2018-04-17 23:07 UTC
Labels: area: router
