### ISSUE TITLE
`Component.preserveWhitespace = false` is too aggressive and not context aware

### ISSUE THREAD

**Issue by cedx** [dart-lang/angular#804] opened 2018-01-27 00:50 UTC
Same issue as the TypeScript flavor of Angular: https://github.com/angular/angular/issues/21049
(read the feed for the full explanation of the problem).

I've tried to apply `preserveWhitespace: false` to my components, and ALL OF THEM have rendering glitches (i.e. words linked together).

A markup like: `Foo <strong>Bar</strong> Baz` (display: "Foo **Bar** Baz")...
...is processed to: `Foo<strong>Bar<strong>Baz` (display: "Foo**Bar**Baz").

If I want to have a proper display of my texts, I need to add an insane amount of `&ngsp;`/`&nbsp;`.

I think that `preserveWhitespace: false` should ignore the (first) preceding/leading whitespace before/after tags within an [inline formatting context](https://www.w3.org/TR/CSS22/visuren.html#inline-formatting).

**Comment by matanlurey** [comment] 2018-01-27 00:55
That's surprising that _all_ of them have glitches. Could you just use `: true` on some?

/cc @alorenzen

**Comment by alorenzen** [comment] 2018-01-27 01:04
Because of the need for using an internationalization library like `package:intl`, most of our clients aren't actually doing a lot of inline text formatting in their templates. So we haven't found this to be an issue in practice for most teams.

I personally don't like the idea of treating some tags differently than others. Then, we're getting back towards being a full HTML compliant parser, which is certainly **not** a goal.

**Comment by cedx** [comment] 2018-01-27 14:05
> That's surprising that all of them have glitches.

Unfortunately, the project I'm working on has inline tags in almost every component template. I have control over the Dart code but not the HTML design (there's a lot of `<strong>`, `<em>` and other inline tags).

> most of our clients aren't actually doing a lot of inline text formatting in their templates

I had the opposite experience. For example, in my previous job, the translation was done by external translators using the [Smartling](https://www.smartling.com) system, which has a smart editor that is "HTML aware" (it properly extracts and shows text from the HTML tags, and insert the translations back into those tags).
So, it was very common to embed HTML in source messages (like `<strong>` tags, but also `<a>` links: this allows you to translate an entire content, instead of dividing that content into X sections to translate).

If you look at the [original AngularTS issue](https://github.com/angular/angular/issues/21049#issuecomment-352130512), you'll see that `preserveWhitespace = false` is also problematic in some translation contexts.

> Then, we're getting back towards being a full HTML compliant parser, which is certainly not a goal.

I like the @Goodwine 's proposal of introducing another property (let's say `spaceCollapsing`, or change the existing `preserveWhitespace` property) that let customize the whitespace processing:
- `preserve` == `preserveWhitespace = true`
- `remove` == `preserveWhitespace = false`
- `collapse` : whitespace is reduced to a single space (thus preserving inline formatting contexts)

This change should be lightweight and easy to implement.

**Comment by furrary** [comment] 2018-02-05 13:14
> A markup like: Foo \<strong>Bar\</strong> Baz (display: "Foo <strong>Bar</strong> Baz")...
...is processed to: Foo\<strong>Bar\</strong>Baz (display: "Foo<strong>Bar</strong>Baz").

I find this really counter intuitive. IMO, if AngularDart aims to be<b>productive</b>this is not the way to go. We still use `.html`, so we need to respect some of its fundamental. 

> Because of the need for using an internationalization library like package:intl, most of our clients aren't actually doing a lot of inline text formatting in their templates. So we haven't found this to be an issue in practice for most teams.

It may not be your intention, but these sentences make me feel like the Dart team only care about large companies who write websites in global scale and don't really care about other people out there.

**Comment by matanlurey** [comment] 2018-02-05 17:49
@furrary:

> but these sentences make me feel like the Dart team only care about large companies who write websites in global scale and don't really care about other people out there.

To be clear, you can _always_ use `preserveWhitespace: true`.

We need to be careful here, because we really don't want this to end up being _too_ configurable (i.e. too many states or an enum of options), and at the same time, don't want it to be confusing (it clearly is today, I agree with you here). I'll speak to the rest of the team this week and try to get a consensus on how to move forward.

**Comment by Goodwine** [comment] 2018-02-05 23:11
I disagree, the `preserveWhitespace:false` feature is buggy IMO.

The reason for its existence is letting us write readable HTML but have the compiler take care of things, basically removing all **extra** spaces.
The problem is that it's removing more than it should, and it's breaking expectations. It *must* render exactly the same thing regardless of the `preserveWhitespace` setting (again, IMO).

If for whatever reason this buggy behavior is seen as a feature to others. Then I believe that the behavior for `preserveWhitespace:true` should change to normalize all template whitespaces so we can get as much binary size reduction as possible but without being buggy.

**Comment by matanlurey** [comment] 2018-02-06 04:51
Just so nobody is frustrated, we have consensus we should do _something_.

The primary maintainer of the AST code (@alorenzen) is out for a couple weeks, and I'd rather not make any decisions until he returns. Continue to please add your comments here on this bug, and we'll hopefully circle back soon.

**Comment by matanlurey** [comment] 2018-02-08 00:26
We've decided @alorenzen will look at this when he gets back ;)

**Comment by matanlurey** [comment] 2018-02-27 06:22
General concepts from the last review:

- We'll do this.
- We'll do it as a visitor in `angular_ast`.
- We'll have a rough list of requirements:

* [ ] Remove whitespace before/after any opening or closing tag:

```html
<div>
  <span>
    Hello World!
  </span>
</div>
``` 

to

```html
<div><span>Hello World!</span></div>
```

* [ ] Collapse whitespace to a maximum of 1 between text and interpolations:

```html
<span>
  Hello
  {{name}}
  !
</span>
```

to

```html
<!-- Notice we got rid of all \n, which is probably always safe here. -->
<span>Hello {{name}}!</span>
```

**Comment by matanlurey** [comment] 2018-02-27 06:25
Some ideas: https://kangax.github.io/html-minifier/

**Comment by matanlurey** [comment] 2018-02-28 00:03
I'm going to own this.

**Comment by Goodwine** [comment] 2018-02-28 00:09
I noticed on your previous email you had an example where
```html
<span>
  some text
</span>
```
transformed to 
```html
<span>some text</span>
```

And you mentioned that all new lines should be removed.
Maybe you also already thought of this but it's worth pointing out an edge case which is having multiple tags together and relying on how browsers handle whitespaces, like:

```html
<span>
  some text
</span>
<span>
  other text
</span>
```
should become
```html
<span>some text</span> <span>some text</span>
```
or "more correctly"
```html
<span> some text </span> <span> some text </span>
```

**Comment by matanlurey** [comment] 2018-02-28 20:59
@Goodwine:

> Maybe you also already thought of this but it's worth pointing out an edge case which is having multiple tags together and relying on how browsers handle whitespaces, like.

I'd prefer to implement mostly what https://kangax.github.io/html-minifier/ does.

I don't think keeping the newlines as spaces is what most people expect.

**Comment by Goodwine** [comment] 2018-02-28 21:05
@matanlurey 
There are many settings in that minifier, the default settings collapses `\n` into a single space.

**Comment by matanlurey** [comment] 2018-02-28 21:06
This seems reasonable:

![screen shot 2018-02-28 at 1 06 17 pm](https://user-images.githubusercontent.com/168174/36813086-344d3556-1c88-11e8-862d-9db644aba3aa.png)

WDUT @Goodwine

**Comment by Goodwine** [comment] 2018-02-28 21:24
Hm, actually, I just checked again and the minifier actually does work :D, would your implementation do the same?

![image](https://user-images.githubusercontent.com/2022649/36813804-8e335436-1c8a-11e8-8fe3-4966e6fadfa1.png)

**Comment by ninachen** [comment] 2018-02-28 22:36
re: collapsing newlines into a single space

I recognize that this is the existing behavior of HTML, but I'll echo @matanlurey in that it's not always expected -- or desired -- that newlines are collapsed into a single space. See [my comment above](https://github.com/dart-lang/angular/issues/804#issuecomment-363217553).

This seems to be a case of where it's not possible to meet all the use cases. :)

Additionally, I'm confused by the example shown in the [last minify example](https://github.com/dart-lang/angular/issues/804#issuecomment-369387848), as the newline between the spans gets removed in the first pair but is converted to a single space in the second pair. Is that expected behavior?

**Comment by cedx** [comment] 2018-03-01 11:32
I had the opportunity to use HTML Minifier on several projects: if all options are implemented, the output should be fine whatever the requirements. See the `Conservative collapse` option.

**Comment by matanlurey** [comment] 2018-03-06 01:12
@ninachen:

> This seems to be a case of where it's not possible to meet all the use cases. :)

I'm going to be a bit conservative, so at least it won't be (as) confusing.

> I had the opportunity to use HTML Minifier on several projects: if all options are implemented, the output should be fine whatever the requirements.

I don't think I will implement all of them (many don't make sense in AngularDart), but if you generally like the output then our take should be almost as good :)

**Comment by rainboxx** [comment] 2018-03-14 08:24
Coming here from the Angular issues linked. The solution showed by @Goodwine looks very strange to me. Imagine you have an `a` tag like this:

```html
<a href="long link">
  here comes link text
</a>
```

You'll end up having:

```html
<a href="long link">here comes link text </a>
```

And suddenly you have an extra space within your link.

The following:

```html
<p>
  this is a paragraph with
  <a href="long link">
    a link inside
  </a>
  and some text
</p>
```

should probably be minified to:

```html
<p>this is a paragraph with <a href="long link">a link inside</a> and some text</p>
```

But:

```html
<div class="foo">
  <div>some things here</div>
  <div>some other things there</div>
</div>
```

should probably be minified to:

```html
<div class="foo"><div>some things here</div><div>some other things there</div></div>
```

You actually don't want to have spaces between tags, since that might result in weirdness when positioning things. AFAIK JSX is producing something like this:

From:

```html
<div className="foo">
  <div>some things here</div>
  <div>some other things there</div>
</div>
```

To:

```html
<div class="foo" data-reactid=".0"><div data-reactid=".0.0">some things here</div><div data-reactid=".0.1">some other things there</div></div>
```

From:

```html
<p>
  this is a paragraph with
  <a href="long link">
    a link inside
  </a>
  and some text
</p>
```

To:

```html
<p data-reactid=".0"><span data-reactid=".0.0">this is a paragraph with</span><a href="long link" data-reactid=".0.1">a link inside</a><span data-reactid=".0.2">and some text</span></p>
```

From:

```html
<p>this is a paragraph with <a href="long link">a link inside</a> and some text</p>
```

To:

```html
<p data-reactid=".0"><span data-reactid=".0.0">this is a paragraph with </span><a href="long link" data-reactid=".0.1">a link inside</a><span data-reactid=".0.2"> and some text</span></p>
```

**Comment by Goodwine** [comment] 2018-03-14 18:39
You are not getting my point,

for anchor tags:
```html
<a>
  whatever
</a>
```
it already behaves like this in every browser
```html
<a>whatever </a>
```

Please look at https://stackblitz.com/edit/angular-uondfj
My point is that `preserveWhitespace: false` should not change how a browser renders a component regardless of what minification strategy it uses.

**Comment by matanlurey** [comment] 2018-05-11 00:19
This has landed in the internal branch, and will be syncing here shortly.

**Closed** 2018-05-11 17:43 UTC
Labels: area: ast, area: compiler, ⛑ breaking change
