### ISSUE TITLE
angular_router 2 hash location strategy URLs differ from 1.x

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#656] opened 2017-09-30 12:38 UTC
When using the `HashLocationStrategy` under the 1.x router, generated hrefs and addresses in the address bar (after following a router link) are consistently of the form

```
/#/foo
```

When using the 2.x router, _generated_ hrefs (from `routerLink`s) are of this form, but when navigating to such links the router rewrites these links by dropping the `/` after the hash:

```
/#foo
```

Is this a desired change in behavior? I don't know if you'll consider this significant or not, but I thought that I'd mention it anyways.

cc @kwalrath @alorenzen @potato620

**Comment by leonsenft** [comment] 2017-11-09 23:38
I'm certain this wasn't intentional. Whether it matters or not, this inconsistency seems like a bug. I'll take a look.

**Comment by leonsenft** [comment] 2017-11-10 00:55
@chalin I can't reproduce the behavior you've described. I see `/#/foo` in all cases. Could you please verify this is still occurring, and if so provide a reproduction case?

**Comment by chalin** [comment] 2017-11-10 02:46
Surely, I'll look into that tomorrow. IIRC, I was running under Angular 4 and the first release of the 2.0 router. Which version did you test this with?

**Comment by leonsenft** [comment] 2017-11-10 16:41
Good observation. I tested against the latest changes internally, so perhaps it was fixed.

Would you be able to check your example with the lastest 5.x to make sure it's not some condition in client code that causes this issue to manifest?

**Comment by nshahan** [comment] 2017-11-14 00:23
I think a reproduction will be a combination of your web server settings and the base ref you have configured. 

__With `<base href="/">` in my index file__
It seems like I can reproduce this behavior in development if my web server isn't hosting the web/ directory as the root folder.
`localhost:8080/path/to/app/web/index.html` <-- Type to access the index.
`localhost:8080/#routepath` <-- In the browser when I click a routeLink.
`localhost:8080/#/routepath` <-- Adding a slash does not work.

If I configure the web server to host the /path/to/app/web/ directory as the root then the url is different as you would expect: 
`localhost:8080/index.html`. <-- Type to access the index.
`localhost:8080/#routepath` <-- In the browser when I click a routeLink.
`localhost:8080/#/routepath` <-- Adding a slash works now. :)

__`const Provider(APP_BASE_HREF, useValue: '/'),` when I bootstrap the app__
If I remove the base ref from the index.html and set the APP_BASE_HREF when I bootstrap the behavior is different. When the web/ directory is not configured as the web server root: `localhost:8080/path/to/app/web/index.html` <-- Type to access the index.
`localhost:8080/path/to/app/web/index.html#/routepath`. <-- Click a link **(notice the order of #/ vs /#)** `localhost:8080/path/to/app/web/index.html/#/routepath` Adding a slash does not work.

Changing the web server settings to host /path/to/app/web/ directory as the root doesn't help here. 
`localhost:8080/index.html`. <-- Type to access the index.
`localhost:8080#/routepath` <-- In the browser when I click a routeLink. **(Same order of #/ vs /#)** 
`localhost:8080/#/routepath` <-- Adding a slash does not work.

**Comment by chalin** [comment] 2017-11-14 01:08
@nshahan - thanks for the detailed report!

**Comment by leonsenft** [comment] 2017-11-17 20:24
Thanks for the details @nshahan. I intend to make all these variants as consistent as possible.

**Comment by leonsenft** [comment] 2017-11-17 23:42
There seems to be some concern about `/#` vs `#/`, but that's not actually the issue. The only issue is what's _after_ the `#`. The domain and fragment _must_ be separated by a path, but a path may or may not have a trailing `/`. This means here

- `localhost:8080#/dashboard` ❌  (try entering this in Chrome, it actually rewrites to the following)
- `localhost:8080/#/dashboard` ✅

the preceding `/` is necessary because it's separating the domain and fragment. But here

- `localhost:8080/web#/dashboard` ✅ 
- `localhost:8080/web/#/dashboard` ✅ 

the preceding `/` is optional since the path is non-empty. 

However, there are two real issues:

1. `HashLocationStrategy` should only be concerned with rewriting the URL fragment; nothing before the `#` should change. The entire point of `HashLocationStrategy` is to enable refreshing any route during development. If you change the actual path you lose this capability. It seems like injecting `APP_BASE_HREF` respects this, but using `<base href="/">` does not and needs fixing.

2. The route path should always have a leading `/`, regardless of the `LocationStrategy`. Again, it seems like `APP_BASE_HREF` respects this, but using `<base href="/">` does not.

On a side note, if you're using `PathLocationStrategy`, it's up to you to ensure the path at which the app is served and the base href match, otherwise you'll see weird routing occur like in your first example @nshahan.

**Comment by leonsenft** [comment] 2017-11-29 00:05
> HashLocationStrategy should only be concerned with rewriting the URL fragment; nothing before the # should change. The entire point of HashLocationStrategy is to enable refreshing any route during development. If you change the actual path you lose this capability. It seems like injecting APP_BASE_HREF respects this, but using <base href="/"> does not and needs fixing.

This is actually out of the router's control. If the `<base>` `href` is set in HTML, the browser will use this for all relative URLs. There's no difference between how the location is updated when using `<base>` vs `APP_BASE_HREF`, it's just that when using the former the browser updates relative to the `<base>` `href`, whereas when using the latter the browser updates relative to the current location.

> The route path should always have a leading /, regardless of the LocationStrategy. Again, it seems like APP_BASE_HREF respects this, but using <base href="/"> does not.

This occurs because `HashLocationStrategy` injects `APP_BASE_HREF`, but doesn't fall back to the `<base>` `href` if not found, and defaults to the empty string. I'll submit a fix for this, but this also got me wondering if the base href should go _before_ the `#`?

**Comment by chalin** [comment] 2017-11-29 14:42
> ... got me wondering if the base href should go before the #?

It is my understanding that an app's base href (regardless of how it is defined), should only affect what goes _before_ the \#. That is, the app base is the path prefix that defines where the app lives. To the right of that prefix is what the router manages based on the chosen location strategy (and the app's current path).

Under HashLocationStrategy, whether a path is rendered as

- `/some/app/base/#/foo/bar` or
- `/some/app/base/#foo/bar`

would seem to be a design choice of canonical (hash)path representation on the part of the router. 

By the way,

- `/some/app/base#foo/bar` works just fine for the examples I've tried -- e.g., [webdev-dartlang-org-dev.firebaseapp.com/examples/toh-5#heroes](https://webdev-dartlang-org-dev.firebaseapp.com/examples/toh-5#heroes) (which uses the 2.0 router)

Under HashLocationStrategy the \# acts like a path separator, so I don't see the need to have an extra `/` after it.

Maybe the choice comes down to backwards compatibility with the 1.x router? But how many production apps use HashLocationStrategy, and of those that do, how many are likely to break if there is no `/` following the \#? Probably very few, if any.

Just to clarify: my goal in opening this issue wasn't to suggest that the router 2.0's use of `#foo` was wrong, but rather that the 2.0 router isn't (self-)consistent. I.e., it sometimes uses `#/foo` and then `#foo` at other times. Whatever the canonical hash path representative is chosen to be, it should be used consistently throughout.

**Comment by leonsenft** [comment] 2017-11-29 18:28
> It is my understanding that an app's base href (regardless of how it is defined), should only affect what goes before the #. That is, the app base is the path prefix that defines where the app lives. To the right of that prefix is what the router manages based on the chosen location strategy (and the app's current path).
>
> Under HashLocationStrategy, whether a path is rendered as
>
> /some/app/base/#/foo/bar or
> /some/app/base/#foo/bar
> would seem to be a design choice of canonical (hash)path representation on the part of the router.

You're right, so this is actually a mistake in the router's current design, since it attempts to place the `<base href>` to the right of the `#`.

> Under HashLocationStrategy the # acts like a path separator, so I don't see the need to have an extra / after it.

Hmm that's actually a good point!

> Maybe the choice comes down to backwards compatibility with the 1.x router? But how many production apps use HashLocationStrategy, and of those that do, how many are likely to break if there is no / following the #? Probably very few, if any.

I actually don't think this will break anything. In all cases, the `/` is optional; both URLs work.

> Just to clarify: my goal in opening this issue wasn't to suggest that the router 2.0's use of #foo was wrong, but rather that the 2.0 router isn't (self-)consistent. I.e., it sometimes uses #/foo and then #foo at other times. Whatever the canonical hash path representative is chosen to be, it should be used consistently throughout.

Yeah, this inconsistency arises from whether you use `APP_BASE_HREF` or `<base href`>. But the inconsistencies are even bigger than just the single `/` as I pointed out.

---

I'll fix up hash routing to make sure the base href is used consistently.

**Comment by leonsenft** [comment] 2017-12-08 23:19
So it turns out the inconsistencies between `APP_BASE_HREF` and `<base href>` are very much intentional, since these two serve entirely different purposes.

`<base href>` serves its normal purpose which you can read about [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base).

`APP_BASE_HREF` on the other hand can be used to prefix different apps' routes within the same page with different URL prefixes. The same can't be done with `<base href>` since it would be shared among all the apps.

Furthermore, the inconsistency @chalin reported between 1.x and 2.x can be controlled by changing or omitting the provider for `APP_BASE_HREF`.

If omitted, you'll see `#foo`, but if provided as `const Provider(APP_BASE_HREF, useValue: '/')`, you'll see `#/foo`.

**Closed by leonsenft** 2017-12-08 23:19 UTC
Labels: area: router

**Comment by chalin** [comment] 2017-12-09 13:39
> If omitted, you'll see #foo, but if provided as const Provider(APP_BASE_HREF, useValue: '/'), you'll see #/foo.

Ah, that's fine but **the `routerLink` directive doesn't seem to be following this rule**.

Essentially none of the example apps set `APP_BASE_HREF`, and as I mentioned in the opening comment:

> When using the 2.x router, _generated_ hrefs (from `routerLink`s) are of [the `/#/foo`] form, but when navigating to such links the router rewrites these links by dropping the `/` after the hash:
`/#foo`.

**Comment by chalin** [comment] 2017-12-11 21:15
@leonsenft - should I open another issue to track the routerLink inconsistency, or will you reopen this one?

**Comment by leonsenft** [comment] 2017-12-11 21:35
@chalin Hi I was planning to look into this again and possibly reopen, but feel free to create a new issue focused on `RouterLinkDirective`.

**Comment by leonsenft** [comment] 2017-12-12 00:21
@chalin I looked into this and figured out a repro case: https://github.com/dart-lang/angular/issues/748

**Comment by chalin** [comment] 2017-12-12 11:10
Thanks!
