### ISSUE TITLE
TemplateGenerator url encodes package path.

### ISSUE THREAD

**Issue by pratikpparikh** [dart-lang/angular#735] opened 2017-12-01 07:20 UTC
Dear Contributors, I am seeing the following in my deps/debug/angular/lib/src/module.template.dart.  Seems to be a bug in the template generator.  Following the error i also included my pubspec as well just for reference.  I am using SDK 2.0.0-dev.8.0 on windows 10, webstorm2017.2.5 in case that information is needed.

// *** EXPERIMENTAL ** Injector Generator [START]
import 'package:angular/src/di/injector/injector.dart' as _i1;
import '..%5Cplatform%5Cbrowser%5Cexceptions.dart' as _i2;
import '..%5Csecurity%5Cdom_sanitization_service_impl.dart' as _i3;
import '..%5Ccore%5Capplication_ref.dart' as _i4;
import '..%5Ccore%5Clinker%5Capp_view_utils.dart' as _i5;
import '..%5Ccore%5Clinker%5Ccomponent_loader.dart' as _i6;
import '..%5Cplatform%5Cdom%5Cevents%5Cevent_manager.dart' as _i7;
import '..%5Cfacade%5Cexception_handler.dart' as _i8;
import '..%5Ccore%5Csecurity.dart' as _i9;
import '..%5Csecurity%5Cdom_sanitization_service.dart' as _i10;
import '..%5Ccore%5Czone%5Cng_zone.dart' as _i11;
import '..%5Cdi%5Cinjector%5Cinjector.dart' as _i12;
import 'modules.dart' as _i13;
import '..%5Ccore%5Ctestability%5Ctestability.dart' as _i14;

name: example_console
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: prati <email@example.com>

environment:
  sdk: '>=2.0.0-dev.8.0 <2.0.0'
dependencies:
  angular: 5.0.0-alpha+1
  angular_components: 0.9.0-alpha+1
  angular_forms: 1.0.1-alpha+1
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  sass_builder: ^1.0.0
dependency_overrides:
  # Necessary with angular: 5.0.0-alpha+1 dependency.
  analyzer: ^0.31.0-alpha.1
dev_dependencies:
  angular_test: ^1.0.2-alpha+1
  webdriver: ^1.2.1
transformers:
- sass_builder
- angular:
    entry_points: web/main.dart
- $dart2js:
    commandLineOptions: [--trust-type-annotations, --trust-primitives, --show-package-warnings, --dump-info]
- dart_to_js_script_rewriter

Regards,

**Comment by matanlurey** [comment] 2017-12-01 14:57
Duplicate of https://github.com/dart-lang/angular/issues/723.

**Closed by matanlurey** 2017-12-01 14:57 UTC
Labels: resolution: duplicate
