### ISSUE TITLE
Build error: type 'ParsedElementAst' is not a subtype of type 'EmbeddedTemplateAst'. Webdev tells me to report a bug.

### ISSUE THREAD

**Issue by denis-beurive** [dart-lang/angular#1695] opened 2018-12-26 16:04 UTC
In order to route, prioritize, and act on this as soon as possible please include:

* [ ] Dart SDK Version (`dart --version`): `Dart VM version: 2.1.0 (Unknown timestamp) on "linux_x64"`
* [ ] AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`): `5.0.0`
* [ ] Whether you are using Windows, macOS, or Linux (if applicable): `Linux`
* [ ] Whether you are using Chrome, Safari, Firefox, Edge (if applicable): it is not important (Chrome and Firefox).
* [ ] Any other packages or constraints we should know about

I don't know if this is really a bug. **However, the tool `webdev` tells me to report a bug. Thus, I do so**.

Below, the output of `webdev`:

    [INFO] Starting Build
    [INFO] Updating asset graph completed, took 6ms
    [SEVERE] angular on lib/app_component.dart:
    Unhandled exception in the AngularDart compiler!

    Please report a bug: https://github.com/dart-lang/angular/issues/new
    type 'ParsedElementAst' is not a subtype of type 'EmbeddedTemplateAst'
    [SEVERE] build_web_compilers|ddc on web/main.dartdevc.module:
    Unable to find modules for some sources, this is usually the result of either a
    bad import, a missing dependency in a package (or possibly a dev_dependency
    needs to move to a real dependency), or a build failure (if importing a
    generated file).

    Please check the following imports:

    `import 'package:myapp/app_component.template.dart' as ng;` from myapp|web/main.dart at 2:1

    [SEVERE] build_web_compilers|entrypoint on web/main.dart:
    Unable to find modules for some sources, this is usually the result of either a
    bad import, a missing dependency in a package (or possibly a dev_dependency
    needs to move to a real dependency), or a build failure (if importing a
    generated file).

    Please check the following imports:

    `import 'package:myapp/app_component.template.dart' as ng;` from myapp|web/main.dart at 2:1

    [INFO] Running build completed, took 1.0s
    [INFO] Caching finalized dependency graph completed, took 202ms
    [SEVERE] Failed after 1.2s

You see: "Please report a bug: https://github.com/dart-lang/angular/issues/new"

I am learning AngularDart. The code can be found here : [https://github.com/denis-beurive/angulardart-playground/tree/master/directive-structural](https://github.com/denis-beurive/angulardart-playground/tree/master/directive-structural)

However, I send you a ZIP of the project, since I won't commit the code that does not compile.

[directive-structural.zip](https://github.com/dart-lang/angular/files/2710491/directive-structural.zip)

**Comment by denis-beurive** [comment] 2018-12-27 09:17
I don't know if this information is relevant, however, the same error shows up, but for a different template content (file `lib/app_component.html`) :

    <div *myLister="let list From ['a', 'b', 'c']"></div>
    
    <div *myLister="let list From ['a', 'b', 'c'];"></div>

[directive-structural.zip](https://github.com/dart-lang/angular/files/2712024/directive-structural.zip)

**Comment by leonsenft** [comment] 2019-01-10 20:44
Thanks for the reproduction. This is a duplicate of https://github.com/dart-lang/angular/issues/1502 and has been fixed since 5.1.0.

**Closed by leonsenft** 2019-01-10 20:44 UTC
