### ISSUE TITLE
Broken void elements as component selector

### ISSUE THREAD

**Issue by ilfa** [dart-lang/angular#494] opened 2017-07-04 17:05 UTC
If we try to use [void elements](https://www.w3.org/TR/html51/syntax.html#void-elements) as a component selector:

```
@Component(
    selector: 'input[my-input]',
```

We get error like this:
```
Transform TemplateCompiler on test_component|lib/components/small_rect_component.ng_meta.json threw error: Template parse errors:
line 1, column 20 of SmallRectComponentHost: ParseErrorLevel.FATAL: Void elements do not have end tags "input"
</input>
```

Looks like template compiler creates closing tag `<input></input>` instead self-closing tag `<input />` for void elements.

It wasn't a big problem before https://github.com/dart-lang/angular/issues/481, but now there is no way to bind component on the void element.

**Comment by matanlurey** [comment] 2017-07-04 19:49
`@Component` with attributes is no longer supported. Sorry.

Duplicate of https://github.com/dart-lang/angular/issues/481.

**Comment by zoechi** [comment] 2017-07-04 20:42
@matanlurey according to https://github.com/dart-lang/angular/issues/335#issuecomment-295064177
`selector: 'input[my-input]',` is a valid selector

**Comment by matanlurey** [comment] 2017-07-04 21:08
Ah, my bad.

**Comment by matanlurey** [comment] 2017-07-04 21:09
@ilfa What version of AngularDart are you using?

**Comment by ilfa** [comment] 2017-07-05 08:58
@matanlurey 3.1.0, but this problem was also in Angular 2.2.0 and earlier.

Here is demo app that demonstrates problem https://github.com/izolenta/ang3-attribute-component

**Comment by matanlurey** [comment] 2017-07-05 15:21
Thanks! It's unlikely we are going to immediately fix something that has been changed since 2.2.0 without any issues filed since. There is a new template parser in the works that could potentially solve this issue though. /cc @mk13

**Comment by ilfa** [comment] 2017-07-06 10:28
@matanlurey what the plans about using new template parser?

**Comment by matanlurey** [comment] 2017-07-06 15:32
No concrete plans yet sorry.

**Comment by ilfa** [comment] 2017-07-27 10:52
@matanlurey @mk13 any news?

**Comment by matanlurey** [comment] 2018-02-13 00:17
I believe this is fixed with the new template parser.

**Closed by matanlurey** 2018-02-13 00:17 UTC
Labels: area: compiler, problem: bug
