### ISSUE TITLE
package_resolver 1.0.7 breaks build_runner

### ISSUE THREAD

**Issue by felangel** [dart-lang/angular#1723] opened 2019-02-24 05:51 UTC
* [Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "macos_x64"] Dart SDK Version (`dart --version`)
* [5.0.0] AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`)
* [macOS] Whether you are using Windows, macOS, or Linux (if applicable)

----
```yaml
dependencies:
  angular: ^5.0.0  
  bloc: ^0.9.3

dev_dependencies:
  test: ">=1.3.0 <2.0.0"
  mockito: ^3.0.0
  analyzer: ^0.32.4
  build_runner: ^0.9.0
  build_test: ^0.10.2+5
  build_web_compilers: ^0.4.0+4
  source_span: ^1.4.0
```

`pub run build_runner test --fail-on-severe`

```
[INFO] Generating build script completed, took 336ms
[INFO] Reading cached asset graph completed, took 581ms
[INFO] Checking for updates since last build completed, took 837ms
[SEVERE] build_web_compilers|ddc on package:package_resolver/package_resolver.dartdevc.module:
Error compiling dartdevc module:package_resolver|lib/package_resolver.ddc.js
[error] The imported library ''current_isolate_resolver_stub.dart'' can't have a part-of directive. (package:package_resolver/src/package_resolver.dart, line 14, col 8)
[error] The imported library ''utils_isolate_stub.dart'' can't have a part-of directive. (package:package_resolver/src/utils.dart, line 16, col 8)
```

When I override `package_resolver` version to use 1.0.6 instead of 1.0.7 everything works again.

```yaml
dependencies:
  angular: ^5.0.0  
  bloc: ^0.9.3

dependency_overrides:
  package_resolver: 1.0.6

dev_dependencies:
  test: ">=1.3.0 <2.0.0"
  mockito: ^3.0.0
  analyzer: ^0.32.4
  build_runner: ^0.9.0
  build_test: ^0.10.2+5
  build_web_compilers: ^0.4.0+4
  source_span: ^1.4.0
```
-----

**Comment by alorenzen** [comment] 2019-02-25 22:13
This sounds like an issue with `package_resolver`, not `angular`. Maybe a duplicate of https://github.com/dart-lang/package_resolver/issues/26?

**Closed by alorenzen** 2019-02-25 22:13 UTC
