### ISSUE TITLE
NoSuchMethodError:  Class List<ConstructorElement>' has no instance method 'retype'

### ISSUE THREAD

**Issue by cinaciojr** [dart-lang/angular#1417] opened 2018-06-15 21:06 UTC
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* [2.0.0-dev.63.0] Dart SDK Version (`dart --version`)
* [5.0.0-alpha+14] AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`)
* [Linux] Whether you are using Windows, macOS, or Linux (if applicable)
* [Chrome] Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
* [ ] Any other packages or constraints we should know about

[FINE] angular on lib/app_component.dart:Running Instance of 'Compiler'
[SEVERE] angular on lib/app_component.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
NoSuchMethodError: Class 'List<ConstructorElement>' has no instance method 'retype'.
Receiver: Instance(length:1) of '_GrowableList'
Tried calling: retype()
dart:core                                                                       Object.noSuchMethod

app_component.dart 
class AppComponent implements OnInit {
  final Routes routes;
  final Router router;
  var routeData;
  final name = "Angular Council";
  AppComponent(this.routes, this.router);
  Storage sessionStore = window.sessionStorage;

  @override
  ngOnInit() {
    sessionStore.clear();
    this.routeData = routes.getRouteData();
  }
}

routes.dart  - getRouteData Method:

  getRouteData() {
    var routeData= Map<String,String>();
    for (var route in all) {
      if(route.additionalData == "Home") {continue;}
      if(route.additionalData == null || route.additionalData == "") {continue;}
      routeData[route.additionalData] = route.toUrl();
    }
    return routeData;
  }

**Comment by matanlurey** [comment] 2018-06-15 21:06
Duplicate of https://github.com/dart-lang/angular/issues/1406.

This is fixed in the latest version, `+15`, or you can downgrade to an older SDK to continue using `+13`.

**Closed by matanlurey** 2018-06-15 21:06 UTC
