### ISSUE TITLE
Add one-time binding support

### ISSUE THREAD

**Issue by jolleekin** [dart-lang/angular#686] opened 2017-11-09 14:34 UTC
I currently use one-way bindings extensively to localize the UI. These bindings are only updated once when a component is instantiated. Keeping these bindings live doesn't help anything if not degrades the performance. If these bindings are one-time, Angular doesn't have to process these bindings any further, thus improving the performance.
Examples:
``` html
<h1>{{ resources['my-component']['header'] }}</h1>
<button>{{ resources['common']['add'] }}</button
```

**Comment by leonsenft** [comment] 2017-11-09 20:42
Angular will only update bindings for `final` primitive fields on the first change change detection cycle. Is it possible to create `final` fields for your resources?

```dart
@Component(...)
class MyComponent {
  final String headerTitle = resources['my-component']['header'];
  final String addButtonTitle = resources['common']['add'];
  ...
}
```

```html
<h1>{{headerTitle}}</h1>
<button>{{addButtonTitle}}</button>
```

**Comment by jolleekin** [comment] 2017-11-10 08:34
Creating `final` primitive fields for all resource keys is too painful as there are more than a thousand keys.

There are two possible solutions I can think of.
1. Use an annotation
    ``` dart
    class MyComponent {
      @immutable
      final Map<String, Map<String, dynamic>> resources;
    }
    ```

2. Add a one-time binding syntax. Below is the syntax from [AngularJS 1.x][1]
``` html
<h1>{{ ::resources['my-component']['header'] }}</h1>
<button>{{ ::resources['common']['add'] }}</button
```

[1]: https://docs.angularjs.org/guide/expression#one-time-binding

**Comment by leonsenft** [comment] 2017-11-20 23:15
Hi @jolleekin, another option for your use case specifically would be to implement the `DoCheck` interface on your component. This would allow you to hand-write change detection code only for the fields you're expecting to change, and not pay the cost for the readonly bindings.

**Comment by jolleekin** [comment] 2017-11-25 09:40
There are a lot of live bindings in addition to the resource bindings. By implementing `DoCheck`, does it mean I have to manually check all fields except `resources`? If so, it's really a pain.

**Comment by leonsenft** [comment] 2017-11-27 18:36
Yes, with `DoCheck` you're responsible for change detecting any bindings you expect to change.

**Comment by matanlurey** [comment] 2018-01-24 01:00
Closing as a duplicate of https://github.com/dart-lang/angular/issues/797 for now.

**Closed by matanlurey** 2018-01-24 01:00 UTC
Labels: area: runtime, feedback: discussion, resolution: duplicate, state: needs info
