### ISSUE TITLE
Unable to resolve dependency with code builder

### ISSUE THREAD

**Issue by mkhan-akhan** [dart-lang/angular#460] opened 2017-06-19 11:25 UTC
Angular2 version 3.1.0

Resolving dependencies...
Package dart_style has no versions that match >=0.2.10 <2.0.0 derived from:
- angular2 3.1.0 depends on version >=0.1.8 <2.0.0
- code_builder 1.0.3 depends on version >=0.2.10 <2.0.0

**Comment by matanlurey** [comment] 2017-06-20 02:42
Seems to be compatible to me. It's likely you have some other conflicting dependency.

**Comment by zoechi** [comment] 2017-06-20 03:33
It's a dup of dart-lang/code_builder#113

**Comment by matanlurey** [comment] 2017-07-20 00:13
Duplicate of dart-lang/code_builder#113,

**Closed by matanlurey** 2017-07-20 00:13 UTC
Labels: state: needs info
