### ISSUE TITLE
hacker_news_pwa: Opening comments in a new tab is broken

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/angular#1108] opened 2018-03-22 07:21 UTC
I commented this in https://github.com/dart-lang/angular/issues/1100 too, but apparently it was ignored, so I'll create a new issue here.

* Opening the comments list in a new tab, or going directly to for instance https://dart-hn.firebaseapp.com/item/16640357 just gives a list as also shown in https://github.com/dart-lang/angular/issues/1100.

* In addition to this, for some items where clicking the headline should go to the comment page (e.g. a "Ask HN" post) and I open in a new tab I'm given a blank page (also by going directly to the link e.g. https://dart-hn.firebaseapp.com/item?id=16646370 --- notice also that the format of the link is different).

* Furthermore, if _not_ opening in a new tab, but simply clicking on 'comments', nothing happens (except for errors in the javascript console). Interestingly enough, opening the page in a incognito window and clicking _does_ work, so it might be some caching problem. Neither reloading not ctrl+reloading fixes it.
The exception in the console is this:
```
js_primitives.dart:28 Running PWA, version: 2017-10-12T23:40:50.000Z
exception_handler.dart:32 EXCEPTION: DeferredLoadException: 'Loading main.dart.js_1.part.js failed: the code with hash 'kXWaHuqAE2FIEQ/b5tNJF6fPl/E=' was not loaded.
event log:
 - _loadHunk: main.dart.js_1.part.js
 - download: main.dart.js_1.part.js from https://dart-hn.firebaseapp.com/main.dart.js_1.part.js
 - download success: main.dart.js_1.part.js
 - missing hunk: main.dart.js_1.part.js (kXWaHuqAE2FIEQ/b5tNJF6fPl/E=)
'
STACKTRACE: 
DeferredLoadException: 'Loading main.dart.js_1.part.js failed: the code with hash 'kXWaHuqAE2FIEQ/b5tNJF6fPl/E=' was not loaded.
event log:
 - _loadHunk: main.dart.js_1.part.js
 - download: main.dart.js_1.part.js from https://dart-hn.firebaseapp.com/main.dart.js_1.part.js
 - download success: main.dart.js_1.part.js
 - missing hunk: main.dart.js_1.part.js (kXWaHuqAE2FIEQ/b5tNJF6fPl/E=)
'
    at Object.b (https://dart-hn.firebaseapp.com/main.dart.js:485:3)
    at mR.$0 (https://dart-hn.firebaseapp.com/main.dart.js:4839:9)
    at mT.$1 (https://dart-hn.firebaseapp.com/main.dart.js:4850:8)
    at jq.og (https://dart-hn.firebaseapp.com/main.dart.js:1556:35)
    at eW.ez (https://dart-hn.firebaseapp.com/main.dart.js:5912:12)
    at ch.ha (https://dart-hn.firebaseapp.com/main.dart.js:8939:5)
    at Object.eval (eval at oX (https://dart-hn.firebaseapp.com/main.dart.js:633:15), <anonymous>:2:44)
    at kK.b3 (https://dart-hn.firebaseapp.com/main.dart.js:5965:12)
    at l8.$0 (https://dart-hn.firebaseapp.com/main.dart.js:5562:16)
    at Object.bH (https://dart-hn.firebaseapp.com/main.dart.js:1457:41)
ORIGINAL EXCEPTION: DeferredLoadException: 'Loading main.dart.js_1.part.js failed: the code with hash 'kXWaHuqAE2FIEQ/b5tNJF6fPl/E=' was not loaded.
event log:
 - _loadHunk: main.dart.js_1.part.js
 - download: main.dart.js_1.part.js from https://dart-hn.firebaseapp.com/main.dart.js_1.part.js
 - download success: main.dart.js_1.part.js
 - missing hunk: main.dart.js_1.part.js (kXWaHuqAE2FIEQ/b5tNJF6fPl/E=)
'

$3 @ exception_handler.dart:32
$2 @ exceptions.dart:11
$1 @ application_ref.dart:342
og @ zone.dart:1138
bU @ zone.dart:1319
aA @ stream_impl.dart:330
c4 @ stream_impl.dart:257
aA @ broadcast_stream_controller.dart:379
q @ broadcast_stream_controller.dart:254
fP @ ng_zone.dart:279
(anonymous) @ VM80:2
al @ zone.dart:1005
bH @ future_impl.dart:548
M @ future_impl.dart:485
M @ future_impl.dart:55
bd @ future_impl.dart:27
U @ async_patch.dart:223
(anonymous) @ router_impl.dart:116
(anonymous) @ async_patch.dart:261
$2 @ async_patch.dart:285
$2 @ async_patch.dart:241
q3 @ zone.dart:1146
ex @ zone.dart:727
h2 @ ng_zone.dart:211
(anonymous) @ VM86:2
ew @ zone.dart:1039
hS @ future_impl.dart:141
$0 @ future_impl.dart:645
bH @ future_impl.dart:666
M @ future_impl.dart:485
M @ future_impl.dart:55
bd @ future_impl.dart:27
U @ async_patch.dart:223
(anonymous) @ router_impl.dart:201
(anonymous) @ async_patch.dart:261
$2 @ async_patch.dart:285
$2 @ async_patch.dart:241
q3 @ zone.dart:1146
ex @ zone.dart:727
h2 @ ng_zone.dart:211
(anonymous) @ VM86:2
ew @ zone.dart:1039
hS @ future_impl.dart:141
$0 @ future_impl.dart:645
bH @ future_impl.dart:666
M @ future_impl.dart:485
M @ future_impl.dart:55
bd @ future_impl.dart:27
U @ async_patch.dart:223
(anonymous) @ router_impl.dart:220
(anonymous) @ async_patch.dart:261
$2 @ async_patch.dart:285
$2 @ async_patch.dart:241
q3 @ zone.dart:1146
ex @ zone.dart:727
h2 @ ng_zone.dart:211
(anonymous) @ VM86:2
ew @ zone.dart:1039
hS @ future_impl.dart:141
$0 @ future_impl.dart:645
bH @ future_impl.dart:666
M @ future_impl.dart:485
M @ future_impl.dart:55
bd @ future_impl.dart:27
U @ async_patch.dart:223
(anonymous) @ router_impl.dart:298
(anonymous) @ async_patch.dart:261
$2 @ async_patch.dart:285
$2 @ async_patch.dart:241
q3 @ zone.dart:1146
ex @ zone.dart:727
h2 @ ng_zone.dart:211
(anonymous) @ VM86:2
ew @ zone.dart:1039
hS @ future_impl.dart:141
$0 @ future_impl.dart:645
bH @ future_impl.dart:666
M @ future_impl.dart:485
M @ future_impl.dart:55
bd @ future_impl.dart:27
U @ async_patch.dart:223
(anonymous) @ app_component.dart:50
(anonymous) @ async_patch.dart:261
$2 @ async_patch.dart:285
$2 @ async_patch.dart:241
q3 @ zone.dart:1146
ex @ zone.dart:727
h2 @ ng_zone.dart:211
(anonymous) @ VM86:2
ew @ zone.dart:1039
hS @ future_impl.dart:141
$0 @ future_impl.dart:645
bH @ future_impl.dart:666
M @ future_impl.dart:485
$2 @ future.dart:372
q3 @ zone.dart:1146
ex @ zone.dart:727
h2 @ ng_zone.dart:211
(anonymous) @ VM86:2
ew @ zone.dart:1039
hS @ future_impl.dart:141
$0 @ future_impl.dart:645
bH @ future_impl.dart:666
cj @ future_impl.dart:477
$0 @ future_impl.dart:507
$0 @ ng_zone.dart:177
of @ zone.dart:1126
ev @ zone.dart:713
h0 @ ng_zone.dart:191
(anonymous) @ VM84:2
a1 @ zone.dart:1023
aK @ zone.dart:925
$0 @ zone.dart:965
tO @ schedule_microtask.dart:41
u1 @ schedule_microtask.dart:50
$1 @ async_patch.dart:53
$0 @ js_helper.dart:2447
bi @ isolate_helper.dart:475
f7 @ isolate_helper.dart:59
uL @ js_helper.dart:2447
(anonymous) @ js_helper.dart:2482
childList (async)
$1 @ async_patch.dart:70
q7 @ async_patch.dart:30
mv @ zone.dart:1187
fN @ zone.dart:765
(anonymous) @ VM90:2
ao @ zone.dart:1082
ap @ future_impl.dart:506
ar @ future_impl.dart:40
$0 @ js_helper.dart:3801
$0 @ js_helper.dart:2445
bi @ isolate_helper.dart:475
f7 @ isolate_helper.dart:59
uL @ js_helper.dart:2445
(anonymous) @ js_helper.dart:2482
load (async)
addEventListener @ VM53:15
tN @ js_helper.dart:3870
$1 @ js_helper.dart:3764
p6 @ list.dart:162
uU @ js_helper.dart:3770
(anonymous) @ app_component.dart:51
(anonymous) @ async_patch.dart:261
$2 @ async_patch.dart:285
$1 @ async_patch.dart:236
og @ zone.dart:1134
ez @ zone.dart:720
ha @ ng_zone.dart:201
(anonymous) @ VM88:2
b3 @ zone.dart:1031
$0 @ future_impl.dart:129
bH @ future_impl.dart:662
$0 @ future_impl.dart:342
$0 @ ng_zone.dart:177
of @ zone.dart:1126
ev @ zone.dart:713
h0 @ ng_zone.dart:191
(anonymous) @ VM84:2
a1 @ zone.dart:1023
aK @ zone.dart:925
$0 @ zone.dart:965
tO @ schedule_microtask.dart:41
u1 @ schedule_microtask.dart:50
$1 @ async_patch.dart:53
$0 @ js_helper.dart:2447
bi @ isolate_helper.dart:475
f7 @ isolate_helper.dart:59
uL @ js_helper.dart:2447
(anonymous) @ js_helper.dart:2482
childList (async)
$1 @ async_patch.dart:70
q7 @ async_patch.dart:30
mv @ zone.dart:1187
fN @ zone.dart:765
(anonymous) @ VM90:2
ao @ zone.dart:1082
c2 @ future_impl.dart:341
cA @ future_impl.dart:250
pU @ async_patch.dart:255
W @ async_patch.dart:191
aa @ router_impl.dart:116
cr @ router_impl.dart:111
dU @ router_impl.dart:105
ig @ router_link_directive.dart:77
(anonymous) @ VM92:2
$0 @ app_view.dart:660
of @ zone.dart:1126
ev @ zone.dart:713
h0 @ ng_zone.dart:191
(anonymous) @ VM84:2
a1 @ zone.dart:1023
aK @ zone.dart:925
$1 @ ng_zone.dart:364
$0 @ js_helper.dart:2447
bi @ isolate_helper.dart:475
f7 @ isolate_helper.dart:59
uL @ js_helper.dart:2447
(anonymous) @ js_helper.dart:2482
```

I'm on Chrome in Linux.

**Comment by matanlurey** [comment] 2018-03-22 16:52
Thanks @jensjoha!

**Comment by leonsenft** [comment] 2018-03-22 20:09
Thanks @jensjoha. I didn't mean to ignore your comment in the other issue. I misinterpreted it as a confirmation of the problem on Linux.

There are three separate issues here. The first is the original issue you pointed out. Our prefetch logic is broken for any page that isn't a feed.

The second issue seems like a regression on https://github.com/dart-lang/angular/issues/954.

The third issue is because our the link comes directly from Hacker News, so we need to rewrite it to match our URL scheme. Filed here: https://github.com/dart-lang/angular/issues/1115

**Comment by leonsenft** [comment] 2018-03-27 17:53
Closed by https://github.com/dart-lang/angular/pull/1118.

**Closed by leonsenft** 2018-03-27 17:53 UTC
Labels: area: examples, ☄ problem: bug
