### ISSUE TITLE
Support a sharding API

### ISSUE THREAD

**Issue by LorenVS** [dart-lang/angular#887] opened 2018-02-14 00:34 UTC
Our AngularDart application is embedded on a page with other frameworks. Those other frameworks dynamically request content from the AngularDart application, and that content is spread throughout the DOM. In order to facilitate this, we depend on a number of unsupported/unstable APIs. It is worth exploring how much of this could be stabilized.

First, we create a root injector and initialize Angular. `rootInjector`, `bootstrapLegacyModule` and `initAngular` are all unsupported APIs.

```
final injector = rootInjector(
  (parent) => ReflectiveInjector.resolveAndCreate([
    bootstrapLegacyModule
  ], parent));
initAngular(injector);
```

We then listen on a message stream, and when messages are received dynamically create content using NgFactories. Both `appRef.registerChangeDetector` and `appRef.unregisterChangeDetector` are unsupported (and actually aren't public at all).

```
Injector injector = ...;
NgFactory factory = ...;
final componentRef = componentLoader.loadDetached(factory, injector);
appRef.registerChangeDetector(componentRef.changeDetectorRef);
componentRef.onDestroy(() {
  appRef.unregisterChangeDetector(componentRef.changeDetectorRef);
});
```

We then relocate `componentRef.location` to some other location in the DOM.

Is there a stable path forward for this sort of usage?

**Comment by matanlurey** [comment] 2018-02-14 00:35
/cc @TedSander @nshahan 

We've talked about having a stable "sharding" API for these advanced use cases.

... but we don't have anything concrete. Do you have a proposal or API you'd like to see?

**Comment by LorenVS** [comment] 2018-02-14 00:40
Optimally, I would like to see the the first code sample combined into a single public API, optimally taking a list of providers as an argument. I'm not sure how that would impact the planned DI changes though. I've heard that eventually the only way to create a root injector will by by creating a root component, but that kind of defeats this usage pattern by default.

`registerChangeDetector` and `unregisterChangeDetector` are probably more specific than need be. Maybe we can just expose`ApplicationRef.attachComponent(ComponentRef)` and `ApplicationRef.detachComponent(ComponentRef)`?

**Comment by matanlurey** [comment] 2018-02-14 00:41
Definitely taking providers as an argument is out. You could use `@GenerateInjector`:

```dart
import 'my_file.template.dart' as ng;

@GenerateInjector(const [
  const Provider(A, useClass: APrime),
])
// The generated factory is your method's name, suffixed with `$Injector`.
final InjectorFactory example = example$Injector;
```

... if that part works for you, hiding the complexity of attach/detach seems easy enough.

**Comment by LorenVS** [comment] 2018-02-14 00:43
Does that mean that the `bootstrapSharded`(or whatever) call would take an Injector as a parameter? Would the root Angular injector become a child of that injector?

**Comment by matanlurey** [comment] 2018-02-14 00:45
@LorenVS:

> Does that mean that the `bootstrapSharded`(or whatever) call would take an Injector as a parameter? 

That sounds reasonable. Something like:

```dart
??? bootstrapSharded({
  InjectorFactory rootApplicationInjector,
}) => ...
```

> Would the root Angular injector become a child of that injector?

The parent, not the child.

**Comment by LorenVS** [comment] 2018-02-14 00:46
How would you get a reference to the created injector? Wouldn't ApplicationRef.injector return Angular's injector, which wouldn't be able to provide anything from the user supplied injector

**Comment by matanlurey** [comment] 2018-02-14 00:59
No, it would return the user-supplied injector, whose parent will be the Angular injector.

Here is an example internally:

```dart
@GenerateInjector(const [
  HackerNewsService,
  routerProviders,
])
final InjectorFactory hackerNewsApp = ng.hackerNewsApp$Injector;

void main() {
  // This would be bootstrapSharded in your example.
  bootstrapFactory(
    app.AppComponentNgFactory,
    hackerNewsApp,
  );
}
```

**Comment by LorenVS** [comment] 2018-02-14 01:02
In that case this seems like it would work for us

**Comment by matanlurey** [comment] 2018-02-14 01:03
Great. Go ahead and experiment with `@GenerateInjector`.

I'll convene the Jedi council to figure out what API we want to formally support.

**Comment by matanlurey** [comment] 2018-02-21 23:12
This is accepted!

**Comment by matanlurey** [comment] 2018-04-12 03:18
For our own note, this is ~roughly the cause of https://github.com/dart-lang/angular/issues/1227.

... given that we have users that rely on this functionality, we should at least support a formal low-level sharding API (i.e. not in `experimental.dart`), even if users built on top of it further, and of course test the API well.

**Comment by cvintila** [comment] 2018-06-08 09:27
Hi Matan, I'm interested in this. We are currently looking to switch the majority of our code over to angulardart. However, we need to do it in an incremental fashion. We are using a .NET CMS and would like the CMS to render component tags and then we manually bootstrap them using JS(maybe provide some config) after page load. Is this doable?

**Comment by matanlurey** [comment] 2018-10-09 21:15
I am going to close as a duplicate of the new https://github.com/dart-lang/angular/issues/1635, where we will tackle application-level settings, potentially also including something like sharding and/or multiple entrypoints.

**Closed by matanlurey** 2018-10-09 21:15 UTC
Labels: area: runtime, ⚡new feature
