### ISSUE TITLE
Use List<Object> instead of List in component providers

### ISSUE THREAD

**Issue by ranquild** [dart-lang/angular#610] opened 2017-08-31 07:23 UTC
In Component annotation `providers` parameter is specified as `List`. This requires to write code like this in strong mode with `implicit-dynamic` disabled: `@Component(providers: <Object>[MyType])`. Please change parameter type to `List<Object>` so it is not required to use `<Object>` anymore.

**Comment by matanlurey** [comment] 2017-08-31 18:01
Duplicate of #402

**Closed by matanlurey** 2017-08-31 18:01 UTC
