### ISSUE TITLE
dart Failed assertion: boolean expression must not be null on Firefox v70

### ISSUE THREAD

**Issue by hamedsbt** [dart-lang/angular#1859] opened 2019-09-12 21:26 UTC
I'm newbie in angularDart, I created a simple project and it has not any issue with chrome-based browser(s) but in the Firefox v70 has **error:**

```EXCEPTION: Failed assertion: boolean expression must not be null
STACKTRACE: 
dart:sdk_internal 8969:25                                                           replaceAll]
package:angular/src/bootstrap/..%5Ccore%5Clinker%5Cstyle_encapsulation.dart 130:29  _flattenStyles
package:angular/src/bootstrap/..%5Ccore%5Clinker%5Cstyle_encapsulation.dart 123:7   _flattenStyles
package:angular/src/bootstrap/..%5Ccore%5Clinker%5Cstyle_encapsulation.dart 96:66   [_appendStyles]
package:angular/src/bootstrap/..%5Ccore%5Clinker%5Cstyle_encapsulation.dart 52:5    __
package:angular/src/bootstrap/..%5Ccore%5Clinker%5Cstyle_encapsulation.dart 66:28   scoped
package:MediaWatchList/app_component.template.dart 95:81                            initComponentStyles
package:MediaWatchList/app_component.template.dart 38:5                             new
package:MediaWatchList/app_component.template.dart 114:19                           build
package:angular/src/bootstrap/..%5Ccore%5Clinker%5Capp_view.dart 258:12             createHostView
package:angular/src/bootstrap/..%5Ccore%5Clinker%5Ccomponent_factory.dart 104:20    create
package:angular/src/bootstrap/..%5Ccore%5Capplication_ref.dart 70:41                <fn>
package:angular/src/bootstrap/..%5Ccore%5Cchange_detection%5Chost.dart 247:26       <fn>
package:angular/src/core/change_detection/..%5Czone%5Cng_zone.dart 132:18           <fn>
dart:sdk_internal 28207:14                                                          run
package:angular/src/core/change_detection/..%5Czone%5Cng_zone.dart 129:18           [_run]
dart:sdk_internal 28413:14                                                          run
package:angular/src/core/change_detection/..%5Czone%5Cng_zone.dart 291:23           run
package:angular/src/bootstrap/..%5Ccore%5Capplication_ref.dart 139:52               runInZone
package:angular/src/bootstrap/..%5Ccore%5Cchange_detection%5Chost.dart 245:5        run
package:angular/src/bootstrap/..%5Ccore%5Capplication_ref.dart 69:23                bootstrap
package:angular/src/bootstrap/run.dart 207:16                                       runApp
main.dart 5:3                                                                       main$
dwds/src/injected/client.js 26095:16                                                call$0
dwds/src/injected/client.js 8103:33                                                 <fn>
dwds/src/injected/client.js 3096:17                                                 <fn>
dwds/src/injected/client.js 11462:12                                                call$2
dwds/src/injected/client.js 11448:32                                                call$1
dwds/src/injected/client.js 12775:18                                                runUnary$2$2
dwds/src/injected/client.js 11835:61                                                call$0
dwds/src/injected/client.js 3197:104                                                _Future__propagateToListeners
dwds/src/injected/client.js 11665:11                                                _complete$1
dwds/src/injected/client.js 11505:10                                                complete$1
dwds/src/injected/client.js 11419:26                                                complete$1
dwds/src/injected/client.js 3069:17                                                 _asyncReturn
dwds/src/injected/client.js 8226:24                                                 <fn>
dwds/src/injected/client.js 3096:17                                                 <fn>
dwds/src/injected/client.js 11462:12                                                call$2
dwds/src/injected/client.js 11448:32                                                call$1
dwds/src/injected/client.js 12775:18                                                runUnary$2$2
dwds/src/injected/client.js 11835:61                                                call$0
dwds/src/injected/client.js 3197:104                                                _Future__propagateToListeners
dwds/src/injected/client.js 11764:9                                                 call$0
dwds/src/injected/client.js 3253:21                                                 _microtaskLoop
dwds/src/injected/client.js 3259:11                                                 _startMicrotaskLoop
dwds/src/injected/client.js 11368:9                                                 call$1
dwds/src/injected/client.js 1206:26                                                 invokeClosure
dwds/src/injected/client.js 1225:18                                                 <fn>

127.0.0.1:8080:37:21
    error (index):37
    error dart_sdk.js:101850
    Angular 5
    _rootRun dart_sdk.js:28587
    run dart_sdk.js:28207
    _run Angular
    run dart_sdk.js:28413
    Angular 5
    main$ main.dart:5
    call$0 client.js:26095
    main client.js:8103
    protected client.js:3096
    call$2 client.js:11462
    call$1 client.js:11448
    runUnary$2$2 client.js:12775
    call$0 client.js:11835
    _Future__propagateToListeners client.js:3197
    _complete$1 client.js:11665
    complete$1 client.js:11505
    complete$1 client.js:11419
    _asyncReturn client.js:3069
    _getDigests client.js:8226
    protected client.js:3096
    call$2 client.js:11462
    call$1 client.js:11448
    runUnary$2$2 client.js:12775
    call$0 client.js:11835
    _Future__propagateToListeners client.js:3197
    call$0 client.js:11764
    _microtaskLoop client.js:3253
    _startMicrotaskLoop client.js:3259
    call$1 client.js:11368
    invokeClosure client.js:1206
    function client.js:1225
```

Build command **pub run build_runner build --delete-conflicting-outputs** log:

```[INFO] Generating build script completed, took 425ms
[WARNING] Throwing away cached asset graph because the build phases have changed. This most commonly would happen as a result of adding a new dependency or updating your dependencies.
[INFO] Cleaning up outputs from previous builds. completed, took 1.5s
[INFO] Generating build script completed, took 82ms
[INFO] Creating build script snapshot... completed, took 16.2s
[INFO] Building new asset graph completed, took 2.1s
[INFO] Checking for unexpected pre-existing outputs. completed, took 5ms
[INFO] Running build completed, took 50.1s
[INFO] Caching finalized dependency graph completed, took 391ms
[INFO] Succeeded after 50.5s with 6025 outputs (13210 actions)
```

pubspec.yaml file:

```
environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  mdc_web:

dev_dependencies:
  angular_test: ^2.3.0
  sass:
  build_config:
  sass_builder: ^2.1.3
  build_runner: ^1.5.0
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
  test: ^1.6.0
```

**Dart SDK Version**: `Dart VM version: 2.5.0-dev.2.1 (Thu Aug 15 16:05:39 2019 +0200) on "windows_x64"`
**AngularDart Version**: `^5.3.0`

**Comment by leonsenft** [comment] 2019-09-13 17:53
Duplicate of #1828. In short, Dart's dev compiler only supports Chrome (you can still deploy production apps compiled in release mode to all modern browsers). The particular crash you've reported is being tracked here https://github.com/dart-lang/sdk/issues/37492.

**Closed by leonsenft** 2019-09-13 17:53 UTC

**Comment by hamedsbt** [comment] 2019-09-14 12:22
I used command: ```webdev serve --release``` to compile and it works like charm.
Also you can use command: ```webdev build --output web:build``` to put result to build directory under web directory.
Thank you!
