### ISSUE TITLE
Missing selector definition causes unhandled compiler exception

### ISSUE THREAD

**Issue by SecondFlight** [dart-lang/angular#1702] opened 2019-01-02 21:40 UTC
Dart SDK version: `2.1.0`
AngularDart version: `5.2.0`
Windows 10
Chrome 71

If you forget to specify a selector for a component, the compiler hits an internal error instead of giving a proper error message.

I have not tested this with a brand new project, but the project I'm in right now is new as of today and only contains 3 components. I've tried removing the selector on two of them, and the error happens in both cases.

To cause the error, change this:

```dart
@Component(
  selector: 'app-container',
  ...
);
class MyClass{...}
```
to this:
```dart
@Component(
  ...
);
class MyClass{...}
```

-------

```
Creating build script, took 12888ms
[INFO] Setting up file watchers completed, took 25ms
[INFO] Waiting for all file watchers to be ready completed, took 153ms
[INFO] Reading cached asset graph completed, took 509ms
[INFO] Checking for updates since last build completed, took 847ms
[INFO] Running build completed, took 482ms
[INFO] Caching finalized dependency graph completed, took 281ms
[SEVERE] angular on lib/app_component.dart (cached):
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
Invalid argument(s)
[SEVERE] build_web_compilers|entrypoint on web/main.dart (cached):
Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'package:logviewer/app_component.template.dart' as _ref4;` from logviewer|web/main.template.dart at 11:1
`import 'package:logviewer/app_component.template.dart' as ng;` from logviewer|web/main.dart at 9:1


[SEVERE] angular on lib/src/container_picker_component.dart (cached):
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
Invalid argument(s)
[SEVERE] Failed after 804ms
Serving `web` on http://localhost:1234
```

**Comment by jbdeboer** [comment] 2019-01-18 19:38
This is probably fixed now.

**Comment by jbdeboer** [comment] 2019-01-18 20:22
The error you reported is saying that the template.dart file does not exist.  It doesn't exist because the AngularDart template compiler failed earlier with another error and left your app in a bad state.

Was another error reported during the build?  If not, we should investigate to why.

If you can provide a reproduction case (e.g. as a small Git repo), we can investigate further.

**Comment by leonsenft** [comment] 2019-01-18 20:52
This was fixed in https://github.com/dart-lang/angular/pull/1693/commits/e01b5335e25b6d7840ab491aaef63b665b4029ec.

**Closed by leonsenft** 2019-01-18 20:52 UTC
Labels: area: compiler, ☄ problem: bug
