### ISSUE TITLE
Unable to compile/serve angulardart project

### ISSUE THREAD

**Issue by delizondo** [dart-lang/angular#1416] opened 2018-06-15 21:05 UTC
* Dart version: Dart VM version: 2.0.0-dev.63.0 (Fri Jun 15 00:42:43 2018 +0200) on "macos_x64"
* Angular: angular: ^5.0.0-alpha+13
* OS: MacOS
* Browser: Chrome
* IDE: WebStorm 2018.1.5

Yesterday everything was working fine in the project I'm working on, however, today since I tried to build the project I've been getting the following error: 

```
NoSuchMethodError: Class 'List<ConstructorElement>' has no instance method 'retype'.
Receiver: Instance(length:1) of '_GrowableList'
Tried calling: retype()
```

**Comment by matanlurey** [comment] 2018-06-15 21:06
Duplicate of https://github.com/dart-lang/angular/issues/1406.

This is fixed in the latest version, `+15`, or you can downgrade to an older SDK to continue using `+13`.

**Closed by matanlurey** 2018-06-15 21:06 UTC
Labels: resolution: duplicate

**Comment by delizondo** [comment] 2018-06-18 15:20
awesome! thanks @matanlurey
