### ISSUE TITLE
@Input properties are called in an infinite loop

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/angular#1333] opened 2018-05-18 21:25 UTC
* [2.0.0-dev.55 ] Dart SDK Version (`dart --version`)
* [5.0.0-aplha+11 ] AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`)
* [Windows ] Whether you are using Windows, MacOSX, or Linux (if applicable)
* [Chrome ] Whether you are using Chrome, Safari, Firefox, Edge (if appplicable)
* [/ ] Any other packages or constraints we should know about

I've encountered a few places in my code here ```@Input``` parameters seem to be set in an infinite-loop.

Following stack traces, I indeed see an infinite cycle of ```detectChangesInternal()``` being called, inside the generated .template.dart files.

Here's my trigger flow:
There's 2 components, 
* a PC parent component 
* and CC child component

- PC has a HTML template where CC is present, i.e. <cc></cc>
- PC exposes a ```Stream```, I provide a property of CC by using ```AsyncPipe``` <cc [prop]="stream | async">
- CC has a setter, annotated with ```@Input``` for prop, inside the setter body, I add the value to an internal ```Stream``` of CC
- when this internal ```Stream``` triggers its ```Event```, I make a ```HttpRequest``` and fetch some data
- this data completes, and causes a ```ChangeDetector``` event on the app root, which also triggers ```detectChanges``` on all children

At this point, I can see the prop setter being invoked again and again.

So I went looking in the generated .template.dart files,
as expected all components have their own ```detectChangesInternal()``` methods.

Now on most components, there is a uniqueness check, for example in this piece:
```dart
@override
  void detectChangesInternal() {
    ...
    final currVal_1 = _map_0((_pipe_async_0.transform(_ctx.isLoading) == true));
    if (!identical(_expr_1, currVal_1)) {
      _NgClass_0_5.rawClass = currVal_1;
      _expr_1 = currVal_1;
    }
    ...
  }
```

But where I trace the change loop, I see this generated:
```dart
@override
  void detectChangesInternal() {
    final import2.ProjectDetail _ctx = ctx;
    bool firstCheck = (this.cdState == 0);
    final currVal_0 = _pipe_async_0.transform(_ctx.project);
    _ContributionsTab_0_5.setProject = currVal_0;
    _expr_0 = currVal_0;
    if (firstCheck) {
      _ContributionsTab_0_5.ngOnInit();
    }
    _compView_0.detectChanges();
  }
```

```currVal_0``` is never checked to be equal to the previous value, as is the case in many other situations.

I'm quite sure this is the cause for my issue, if the current value is never compared to the old value, I get my infinite loop, where the same value for prop keeps setting.

In this case ```setProject``` sets a ```Project``` class instance, perhaps I just need to add some equality handlers inside this class, so that the Angular builder knows how to compare the item to the previous value?

**Comment by leonsenft** [comment] 2018-05-18 21:53
What change detection strategy are your components using?

**Comment by frankpepermans** [comment] 2018-05-18 21:55
Stateful with ComponentState

**Comment by leonsenft** [comment] 2018-05-18 22:03
I believe this is working as intended then. When using `Stateful` change detection, it's the component's own responsibility to detect changes. Like you mentioned, you should be checking the value assigned to `setProject` to see if it's different than the last value before calling `setState()`.

**Closed** 2018-05-18 22:15 UTC
Labels: resolution: as intended

**Comment by frankpepermans** [comment] 2018-05-19 04:47
Does make sense, was this changed compared to Angular v3?

The app worked fine in dart 1 with angular 3, maybe back then the value was always checked inside the generated code, regardless of the detection type?

**Comment by leonsenft** [comment] 2018-05-21 17:11
I'm guessing that was a mistake that it was being checked for `ComponentState` components, but I'm not certain. Do you have any insight to this change @ferhatb?

**Comment by frankpepermans** [comment] 2018-05-21 17:26
Maybe it *should* be checked though, as @Input should only trigger when a value updates, now it sets the same value over and over anytime change detection kicks in.

I've placed a value check now on all setters, but some Input values are expected to be set only once  logically
