### ISSUE TITLE
Using the wrong preposition in "let" template command crashes

### ISSUE THREAD

**Issue by danielmcquillen** [dart-lang/angular#1335] opened 2018-05-23 03:18 UTC
Dart version: 2.0.0-dev.55.0
MacOSX
Chrome

Noticed that if I mistakenly type invalid syntax like `let blah in blahs` in a template (rather then the correct `let blah of blahs`) it will crash the compiler rather than just report a syntax error.

**Comment by leonsenft** [comment] 2018-05-23 03:30
What version of `package:angular` are you using?

The crash was fixed awhile ago and I even [added a special warning](https://github.com/dart-lang/angular/commit/012b46385c6a73c8475ad84dd08f888ecee7c004#diff-1f554f358a75ba206c49542dd0c50aab) for exactly this mistake since it's so common.  Try updating to a newer release.

**Comment by danielmcquillen** [comment] 2018-05-23 04:25
Strange. I'm using `angular: ^5.0.0-alpha+11` which I thought is the latest. At any rate, good to know the problem was resolved.

**Comment by leonsenft** [comment] 2018-05-23 17:16
Huh, it should have been fixed by that version. I'll see if I can reproduce on the latest version.

**Comment by leonsenft** [comment] 2018-05-23 19:51
I just tried and am not seeing a crash (it does intentionally fail the build).

```
[INFO] Starting Build

[INFO] Updating asset graph...
[INFO] Updating asset graph completed, took 3ms

[INFO] Running build...
[INFO] 5.3s elapsed, 0/1 actions completed.
[SEVERE] angular on lib/app_component.dart:
Template parse errors:
line 1, column 8 of AppComponent: ParseErrorLevel.FATAL: Can't bind to 'ngForIn' since it isn't an input of any bound directive. Please check that the spelling is correct, and that the intended directive is included in the host component's list of directives.

This is a common mistake when using *ngFor; did you mean to write 'of' instead of 'in'?
  <div *ngFor="let value in values">
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Please run `pub upgrade`, and try serving again. If you're still seeing a compiler crash please reopen with a reproduction.

**Closed by leonsenft** 2018-05-23 19:51 UTC
