### ISSUE TITLE
build_runner hangs indefinitely on template parsing error

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1259] opened 2018-04-18 19:46 UTC
_From @krypton-code on April 18, 2018 19:38_

I'm going through the tutorial in this place:
https://webdev-dartlang-org-dev.firebaseapp.com/angular/tutorial/toh-pt1#show-all-hero-properties
as soon as I make changes to the template and try to update the page, I don't get changes. I have to run the command `pub run build_runner serve` again, that to see the changes. I also noticed in other cases that I need to manually reboot the build_runner.

I dare to suggest that this does not work properly. Thank you.

* dependencies:
  * angular: ^5.0.0-alpha

* dev_dependencies:
  * angular_test: ^2.0.0-alpha
  * build_runner: ^0.8.2
  * build_test: ^0.10.0
  * build_web_compilers: ^0.3.6
  * test: ^0.12.30
</br>
* Dart VM version: 2.0.0-dev.48.0 (Unknown timestamp) on "linux_x64"
* Ubuntu 16.04
* Chrome 65.0.3325.181

_Copied from original issue: dart-lang/sdk#32920_

**Comment by matanlurey** [comment] 2018-04-18 19:47
Hi @krypton-code. We are going to need a bit more information to help out.

Can you share a copy of your terminal output when you use `pub run build_runner serve` and change a file?

/cc @natebosch

**Comment by krypton-code** [comment] 2018-04-18 19:50
➜  quickstart git:(master) ✗ pub run build_runner serve
[INFO] Generating build script completed, took 227ms
[INFO] Setting up file watchers completed, took 12ms
[INFO] Waiting for all file watchers to be ready completed, took 49ms
[INFO] Reading cached asset graph completed, took 214ms
[INFO] Checking for updates since last build completed, took 371ms
[INFO] Running build completed, took 15ms
[INFO] Caching finalized dependency graph completed, took 104ms
[INFO] Succeeded after 126ms with 0 outputs
Serving `web` on http://localhost:8080
Serving `test` on http://localhost:8081
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 9ms
[SEVERE] build_web_compilers|ddc on lib/app_component.module:
Error compiling dartdevc module:angular_app|lib/app_component.ddc.js

[error] The name 'hero' is already defined. (package:angular_app/app_component.dart, line 16, col 8)

Please fix all errors before compiling (warnings are okay).
}
[SEVERE] build_web_compilers|ddc on lib/app_component.template.module:
Error compiling dartdevc module:angular_app|lib/app_component.template.ddc.js

[error] The getter 'name' isn't defined for the class 'String'. (package:angular_app/app_component.template.dart, line 54, col 54)

Please fix all errors before compiling (warnings are okay).
}
[WARNING] build_web_compilers|entrypoint on web/main.dart:
Unable to read angular_app|lib/app_component.template.ddc.js, check your console or the `.dart_tool/build/generated/angular_app/lib/app_component.template.ddc.js.errors` log file.
[WARNING] build_web_compilers|entrypoint on web/main.dart:
Unable to read angular_app|lib/app_component.ddc.js, check your console or the `.dart_tool/build/generated/angular_app/lib/app_component.ddc.js.errors` log file.
[INFO] Running build completed, took 5.5s
[INFO] Caching finalized dependency graph completed, took 217ms
[INFO] Succeeded after 5.8s with 14 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 1ms
[SEVERE] build_web_compilers|ddc on lib/app_component.module:
Error compiling dartdevc module:angular_app|lib/app_component.ddc.js

[error] The name 'hero' is already defined. (package:angular_app/app_component.dart, line 16, col 8)

Please fix all errors before compiling (warnings are okay).
}
[SEVERE] build_web_compilers|ddc on lib/app_component.template.module:
Error compiling dartdevc module:angular_app|lib/app_component.template.ddc.js

[error] The getter 'name' isn't defined for the class 'String'. (package:angular_app/app_component.template.dart, line 54, col 54)

Please fix all errors before compiling (warnings are okay).
}
[WARNING] build_web_compilers|entrypoint on web/main.dart:
Unable to read angular_app|lib/app_component.template.ddc.js, check your console or the `.dart_tool/build/generated/angular_app/lib/app_component.template.ddc.js.errors` log file.
[WARNING] build_web_compilers|entrypoint on web/main.dart:
Unable to read angular_app|lib/app_component.ddc.js, check your console or the `.dart_tool/build/generated/angular_app/lib/app_component.ddc.js.errors` log file.
[INFO] Running build completed, took 397ms
[INFO] Caching finalized dependency graph completed, took 67ms
[INFO] Succeeded after 469ms with 14 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 3ms
[INFO] Running build completed, took 581ms
[INFO] Caching finalized dependency graph completed, took 60ms
[INFO] Succeeded after 649ms with 16 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 3ms
[INFO] Running build completed, took 384ms
[INFO] Caching finalized dependency graph completed, took 65ms
[INFO] Succeeded after 457ms with 16 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 4ms
[INFO] Running build completed, took 377ms
[INFO] Caching finalized dependency graph completed, took 68ms
[INFO] Succeeded after 453ms with 16 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 3ms
[SEVERE] build_web_compilers|ddc on lib/app_component.template.module:
Error compiling dartdevc module:angular_app|lib/app_component.template.ddc.js

[error] The getter 'hero' isn't defined for the class 'AppComponent'. (package:angular_app/app_component.template.dart, line 54, col 49)

Please fix all errors before compiling (warnings are okay).
}
[WARNING] build_web_compilers|entrypoint on web/main.dart:
Unable to read angular_app|lib/app_component.template.ddc.js, check your console or the `.dart_tool/build/generated/angular_app/lib/app_component.template.ddc.js.errors` log file.
[INFO] Running build completed, took 322ms
[INFO] Caching finalized dependency graph completed, took 61ms
[INFO] Succeeded after 391ms with 15 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 3ms
[SEVERE] build_web_compilers|ddc on lib/app_component.template.module:
Error compiling dartdevc module:angular_app|lib/app_component.template.ddc.js

[error] The getter 'hero' isn't defined for the class 'AppComponent'. (package:angular_app/app_component.template.dart, line 54, col 49)

Please fix all errors before compiling (warnings are okay).
}
[WARNING] build_web_compilers|entrypoint on web/main.dart:
Unable to read angular_app|lib/app_component.template.ddc.js, check your console or the `.dart_tool/build/generated/angular_app/lib/app_component.template.ddc.js.errors` log file.
[INFO] Running build completed, took 408ms
[INFO] Caching finalized dependency graph completed, took 93ms
[INFO] Succeeded after 511ms with 15 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 3ms
[INFO] Running build completed, took 317ms
[INFO] Caching finalized dependency graph completed, took 68ms
[INFO] Succeeded after 393ms with 16 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 5ms
[INFO] Running build completed, took 555ms
[INFO] Caching finalized dependency graph completed, took 111ms
[INFO] Succeeded after 678ms with 16 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 3ms
[INFO] Running build completed, took 376ms
[INFO] Caching finalized dependency graph completed, took 81ms
[INFO] Succeeded after 465ms with 16 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 3ms
[SEVERE] angular on lib/app_component.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
AngularParserException{NgParserWarningCode.ELEMENT_IDENTIFIER}
[SEVERE] build_web_compilers|ddc on lib/app_component.template.module:

AssetNotFoundException: angular_app|lib/app_component.template.dart
[SEVERE] build_web_compilers|ddc on lib/app_component.template.module:

AssetNotFoundException: angular_app|lib/app_component.template.dart
[INFO] Terminating. No further builds will be scheduled
[INFO] 2m 35s elapsed, 8/9 actions completed.^[[A^C%

**Comment by matanlurey** [comment] 2018-04-18 19:55
So you have reported build errors, such as

`[error] The name 'hero' is already defined. (package:angular_app/app_component.dart, line 16, col 8)`

I recommend using an IDE (IntelliJ - Community or WebStorm) or Visual Studio Code with the Dart Plugin - if you are new to Dart or AngularDart. It will show you many/most compile-time errors earlier and it will be easier to fix problems such as these.

**Comment by chalin** [comment] 2018-04-18 20:05
@krypton-code: maybe you _added_ the declaration

```dart
Hero hero = new Hero(1, 'Windstorm');
```

instead of using it to replace `var hero = 'Windstorm'`? That would match with the error you've mentioned. I'll update the tutorial to make that clearer.

**Comment by krypton-code** [comment] 2018-04-18 20:07
@matanlurey, I apologize, but problem repeat. I use Visual Studio code with Dart Plugin, but I don't get error of linter or other error in editor. Restart helps only `pub run build_runner serve`

![image](https://user-images.githubusercontent.com/6662917/38955116-5578fb34-435c-11e8-92b7-4b34aff95a68.png)

**Comment by krypton-code** [comment] 2018-04-18 20:16
@chalin I understan you, in this case liner return syntax error, conflict duplication of names.

This is valid code. For example, cope 11 line and get error build. If you restart command `pub run build_runner serve`, it will be work.

![image](https://user-images.githubusercontent.com/6662917/38955679-0a72bfce-435e-11e8-9ece-2413706bc87f.png)

**Comment by krypton-code** [comment] 2018-04-18 20:29
@chalin sorry, maybe I can not convey to you the essence of the problem because of my English. In the documentation everything is clearly written. The problem is that the live mode (build_runner) does not work properly.

**Comment by chalin** [comment] 2018-04-18 21:30
@matanlurey - there now appears to be an "Unhandled exception in the AngularDart compiler".

**Comment by natebosch** [comment] 2018-04-18 23:38
Unless the config is changing - things like the pubspec lock, or the build.yaml file (and we should warn if they do) restarting `pub run build_runner serve` should give identical outputs. If you can give a reliable repro for when it's necessary to restart the server we can take a look. The situation as I understand it is:

1. Code is in a certain state (can you share a repo?)
2. Start build_runner serve, build succeeds
3. Make an edit (can you share the specific edit?), watcher picks it up and the build fails
4. Fix the build failure, watcher picks it up but the build still fails
5. Restart build_runner serve and the build runs and succeeds.

Do I have the correct understanding?

**Comment by krypton-code** [comment] 2018-04-19 10:29
@natebosch I not touched config files, just follow the tour.

> 1. Code is in a certain state (can you share a repo?)
> 2. Start build_runner serve, build succeeds
> 3. Make an edit (can you share the specific edit?), watcher picks it up and the build fails
> 4. Fix the build failure, watcher picks it up but the build still fails
> 5. Restart build_runner serve and the build runs and succeeds.
Yes, this is correct understanding.

I pushing code in repo and wrote README about it how to get error in this case: https://github.com/krypton-code/angular-dart-tour

**Comment by krypton-code** [comment] 2018-04-19 20:07
New information. Moving forward on the tour, I came to the conclusion that any manual written HTML, causes a compilation error.

**Comment by krypton-code** [comment] 2018-04-20 15:14
@chalin - There were new details about the error. Compile fail precisely in the case if enter the HTML code without using Emmet (the native plug-in in VSCode). If I use Emmet, then the compile does not fail. It seems to me that the compilation falls precisely at the moment of entering the sign `<`.

**Comment by chalin** [comment] 2018-04-20 15:29
If you could republish your code and tell us the steps to follow to reproduce the problem, that would great!

**Comment by krypton-code** [comment] 2018-04-20 16:04
@chalin I update dart, but the problem remains.
Update repo: https://github.com/krypton-code/angular-dart-tour/tree/master
The code has not been changed, I will show the problem on video:
https://drive.google.com/open?id=12UQn_Zs_NYfCKvqM-jzej_B-mqVa6SKL

```bash
➜  angular-dart-tour git:(master) ✗ dart --version
Dart VM version: 2.0.0-dev.49.0 (Unknown timestamp) on "linux_x64"
➜  angular-dart-tour git:(master) ✗ pub run build_runner serve
Dart 2.0.0-dev.49.0 is incompatible with your dependencies' SDK constraints. Please run "pub get" again.
➜  angular-dart-tour git:(master) ✗ pub get
Resolving dependencies... 
Overriding the upper bound Dart SDK constraint to <=2.0.0-dev.49.0 for the following packages:

archive, args, barback, bazel_worker, boolean_selector, build_barback, build_config, charcode, cli_util, code_transformers, convert, crypto, csslib, dart_style, fixnum, front_end, glob, graphs, html, http, http_multi_server, http_parser, intl, io, isolate, js, json_annotation, kernel, logging, matcher, meta, multi_server_socket, node_preamble, package_config, package_resolver, path, plugin, pool, protobuf, pub_semver, quiver, quiver_hashcode, shelf, shelf_packages_handler, shelf_static, shelf_web_socket, source_map_stack_trace, source_maps, source_span, stack_trace, stream_channel, string_scanner, term_glyph, tuple, typed_data, yaml

To disable this you can set the PUB_ALLOW_PRERELEASE_SDK system environment variable to `false`, or you can silence this message by setting it to `quiet`.
Got dependencies!
Precompiling executables... 
Loading source assets... 
Precompiled angular_test:angular_test.
Precompiled build_runner:graph_inspector.
Precompiled test:test.
Precompiled build_runner:build_runner.
➜  angular-dart-tour git:(master) ✗ pub run build_runner serve
[INFO] Generating build script completed, took 259ms
[INFO] Setting up file watchers completed, took 12ms
[INFO] Waiting for all file watchers to be ready completed, took 112ms
[WARNING] Throwing away cached asset graph due to Dart SDK update.
[INFO] Cleaning up outputs from previous builds. completed, took 146ms
[INFO] Reading cached asset graph completed, took 468ms
[INFO] Building new asset graph completed, took 544ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 0ms
[INFO] Running build completed, took 20.6s
[INFO] Caching finalized dependency graph completed, took 303ms
[INFO] Succeeded after 20.9s with 1441 outputs
Serving `web` on http://localhost:8080
Serving `test` on http://localhost:8081
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 7ms
[INFO] Running build completed, took 314ms
[INFO] Caching finalized dependency graph completed, took 98ms
[INFO] Succeeded after 425ms with 11 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 2ms
[INFO] Running build completed, took 403ms
[INFO] Caching finalized dependency graph completed, took 79ms
[INFO] Succeeded after 490ms with 11 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 5ms
[INFO] Running build completed, took 471ms
[INFO] Caching finalized dependency graph completed, took 90ms
[INFO] Succeeded after 571ms with 11 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 4ms
[SEVERE] angular on lib/app_component.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
AngularParserException{NgParserWarningCode.ELEMENT_IDENTIFIER}
[SEVERE] build_web_compilers|ddc on lib/app_component.template.module:

AssetNotFoundException: angular_app|lib/app_component.template.dart
[SEVERE] build_web_compilers|ddc on lib/app_component.template.module:

AssetNotFoundException: angular_app|lib/app_component.template.dart
[INFO] Terminating. No further builds will be scheduled
[INFO] 1m 0s elapsed, 4/5 actions completed.^C%                                                       
➜  angular-dart-tour git:(master) ✗ 
```

**Comment by leonsenft** [comment] 2018-04-20 16:33
>Unhandled exception in the AngularDart compiler!
>
>Please report a bug: https://github.com/dart-lang/angular/issues/new
>AngularParserException{NgParserWarningCode.ELEMENT_IDENTIFIER}

This actually isn't a bug. We regressed on handling error messages awhile back, and were only printing the error code claiming it was a bug.

As of e6c41400f601279a6c33bb5ee789b59fcc4eaae9 this has been fixed, and you'll see the actual error message, as well as the source span of where the error occurred. Unfortunately this commit is more recent than the latest alpha release. You can either wait until alpha+11 is release, or change your pubspec.yaml to depend directly on the GitHub repo.

The reason you'd see this error code in particular is if your HTML is invalid and the scanner is in a state where it expected an element identifier but there wasn't one. I tried reproducing your example and couldn't get the compiler to produce an error.

**Comment by krypton-code** [comment] 2018-04-20 16:52
@leonsenft - the compiler falls when entering symbol `<` in editor. This can be seen in the video example.

**Comment by matanlurey** [comment] 2018-04-20 17:58
As mentioned, you can't use `<` - that's invalid HTML.

In the next release the error will be more prominent.

**Comment by leonsenft** [comment] 2018-04-20 18:05
If you watch the video they're not trying to enter `<` alone. I think they mean as soon as they type the leading `<` of `<input type="text">` it crashes; it seems like the compiler is running on the first change.

@krypton-code Is your editor perhaps saving on that initial keystroke? When I'm developing build_runner doesn't attempt to rerun until I save the file I'm editing. Does it never attempt to rebuild after the crash?

**Comment by krypton-code** [comment] 2018-04-20 18:18
@matanlurey @leonsenft - from your words, I can conclude that when autosaving is enabled, typing the character '<' causes the compiler to falls, then I end the HTML string and editor once again auto-save works and the compiler tries to recover from the crash, but the process goes to infinity.

Do I understand correctly?

**Comment by leonsenft** [comment] 2018-04-20 19:39
Thanks @krypton-code. There is an issue here and I can confirm it is reproducible. This appears to be isolated to build_runner, as I can only reproduce externally.

To reproduce:
1. Have a functioning app being served.
2. Add `<` to a template and save.
3. build_runner attempts a rebuild which fails as expected. However, it then continues to repeatedly log  `[INFO] <time> elapsed, 4/5 actions completed.`
4. Fix the template by completing the tag or removing the `<` and save.
5. build_runner appears to remain stuck in the previous state repeatedly logging the same message.

I tried reproducing with another compiler error not related to template parsing, and while it still produces an error, compilation doesn't hang on `4/5 actions completed`. There's one notable difference that occurs with parse errors which is at step 3 the following logged:

```
[SEVERE] build_web_compilers|ddc on lib/app_component.template.module:

AssetNotFoundException: foo|lib/app_component.template.dart
```

- @matanl It appears as though when template parsing fails, Angular doesn't produce the .template.dart file which causes build_web_compilers to loop indefinitely and block further recompilation. Perhaps this is related to using the new parser during directive normalization.
- @natebosch Is this behavior a bug or expected when a builder doesn't emit the expected asset? It should at least handle recovering no?

**Comment by natebosch** [comment] 2018-04-21 03:04
This should be fixed by https://github.com/dart-lang/build/pull/1322

Can you run a `pub upgrade` and verify that it is working for you?

**Comment by krypton-code** [comment] 2018-04-21 11:12
@natebosch - I run `pub upgrade` and all works, problem is solved, the compiler to recover from the crash. Thanks for helping.

Console output:

```bash
➜  angular-dart-tour git:(master) pub run build_runner serve    
[INFO] Generating build script completed, took 265ms
[INFO] Setting up file watchers completed, took 12ms
[INFO] Waiting for all file watchers to be ready completed, took 46ms
[INFO] Reading cached asset graph completed, took 281ms
[INFO] Checking for updates since last build completed, took 392ms
[WARNING] Invalidating asset graph due to build script update
[INFO] Cleaning up outputs from previous builds. completed, took 109ms
[INFO] Building new asset graph completed, took 468ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO] Running build completed, took 20.3s
[INFO] Caching finalized dependency graph completed, took 111ms
[INFO] Succeeded after 20.5s with 1441 outputs
Serving `web` on http://localhost:8080
Serving `test` on http://localhost:8081
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 12ms
[INFO] Running build completed, took 113ms
[INFO] Caching finalized dependency graph completed, took 82ms
[INFO] Succeeded after 212ms with 1 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 2ms
[SEVERE] angular on lib/app_component.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
AngularParserException{NgParserWarningCode.ELEMENT_IDENTIFIER}
[SEVERE] build_web_compilers|ddc on lib/app_component.template.module:

AssetNotFoundException: angular_app|lib/app_component.template.dart
[SEVERE] build_modules|modules on lib/app_component.template.module:

AssetNotFoundException: angular_app|lib/app_component.template.dart
[SEVERE] build_web_compilers|ddc on web/main.module:

AssetNotFoundException: angular_app|lib/app_component.template.linked.sum
[WARNING] build_web_compilers|entrypoint on web/main.dart:
Unable to read angular_app|lib/app_component.template.ddc.js, check your console or the `.dart_tool/build/generated/angular_app/lib/app_component.template.ddc.js.errors` log file.
[WARNING] build_web_compilers|entrypoint on web/main.dart:
Unable to read angular_app|web/main.ddc.js, check your console or the `.dart_tool/build/generated/angular_app/web/main.ddc.js.errors` log file.
[INFO] Running build completed, took 202ms
[INFO] Caching finalized dependency graph completed, took 85ms
[SEVERE] Failed after 295ms
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 3ms
[SEVERE] angular on lib/app_component.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
AngularParserException{NgParserWarningCode.ELEMENT_DECORATOR}
[INFO] Running build completed, took 53ms
[INFO] Caching finalized dependency graph completed, took 108ms
[SEVERE] Failed after 166ms
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 2ms
[SEVERE] angular on lib/app_component.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
AngularParserException{NgParserWarningCode.ELEMENT_DECORATOR}
[INFO] Running build completed, took 49ms
[INFO] Caching finalized dependency graph completed, took 85ms
[SEVERE] Failed after 139ms
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 3ms
[SEVERE] angular on lib/app_component.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
AngularParserException{NgParserWarningCode.ELEMENT_DECORATOR}
[INFO] Running build completed, took 46ms
[INFO] Caching finalized dependency graph completed, took 109ms
[SEVERE] Failed after 160ms
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 3ms
[SEVERE] angular on lib/app_component.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
AngularParserException{NgParserWarningCode.ELEMENT_DECORATOR}
[INFO] Running build completed, took 43ms
[INFO] Caching finalized dependency graph completed, took 89ms
[SEVERE] Failed after 138ms
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 3ms
[INFO] Running build completed, took 433ms
[INFO] Caching finalized dependency graph completed, took 114ms
[INFO] Succeeded after 557ms with 10 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 3ms
[INFO] Running build completed, took 57ms
[INFO] Caching finalized dependency graph completed, took 93ms
[INFO] Succeeded after 155ms with 1 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 4ms
[SEVERE] angular on lib/app_component.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
AngularParserException{NgParserWarningCode.ELEMENT_DECORATOR}
[SEVERE] build_web_compilers|ddc on lib/app_component.template.module:

AssetNotFoundException: angular_app|lib/app_component.template.dart
[SEVERE] build_modules|modules on lib/app_component.template.module:

AssetNotFoundException: angular_app|lib/app_component.template.dart
[SEVERE] build_web_compilers|ddc on web/main.module:

AssetNotFoundException: angular_app|lib/app_component.template.linked.sum
[WARNING] build_web_compilers|entrypoint on web/main.dart:
Unable to read angular_app|lib/app_component.template.ddc.js, check your console or the `.dart_tool/build/generated/angular_app/lib/app_component.template.ddc.js.errors` log file.
[WARNING] build_web_compilers|entrypoint on web/main.dart:
Unable to read angular_app|web/main.ddc.js, check your console or the `.dart_tool/build/generated/angular_app/web/main.ddc.js.errors` log file.
[INFO] Running build completed, took 220ms
[INFO] Caching finalized dependency graph completed, took 117ms
[SEVERE] Failed after 347ms
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 1ms
[INFO] Running build completed, took 299ms
[INFO] Caching finalized dependency graph completed, took 85ms
[INFO] Succeeded after 390ms with 10 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 1ms
[INFO] Running build completed, took 302ms
[INFO] Caching finalized dependency graph completed, took 91ms
[INFO] Succeeded after 399ms with 8 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 0ms
[INFO] Running build completed, took 49ms
[INFO] Caching finalized dependency graph completed, took 102ms
[INFO] Succeeded after 153ms with 1 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 3ms
[SEVERE] angular on lib/app_component.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
AngularParserException{NgParserWarningCode.ELEMENT_IDENTIFIER}
[SEVERE] build_web_compilers|ddc on lib/app_component.template.module:

AssetNotFoundException: angular_app|lib/app_component.template.dart
[SEVERE] build_modules|modules on lib/app_component.template.module:

AssetNotFoundException: angular_app|lib/app_component.template.dart
[SEVERE] build_web_compilers|ddc on web/main.module:

AssetNotFoundException: angular_app|lib/app_component.template.linked.sum
[WARNING] build_web_compilers|entrypoint on web/main.dart:
Unable to read angular_app|lib/app_component.template.ddc.js, check your console or the `.dart_tool/build/generated/angular_app/lib/app_component.template.ddc.js.errors` log file.
[WARNING] build_web_compilers|entrypoint on web/main.dart:
Unable to read angular_app|web/main.ddc.js, check your console or the `.dart_tool/build/generated/angular_app/web/main.ddc.js.errors` log file.
[INFO] Running build completed, took 167ms
[INFO] Caching finalized dependency graph completed, took 80ms
[SEVERE] Failed after 258ms
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 3ms
[SEVERE] angular on lib/app_component.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
AngularParserException{NgParserWarningCode.ELEMENT_DECORATOR}
[INFO] Running build completed, took 93ms
[INFO] Caching finalized dependency graph completed, took 111ms
[SEVERE] Failed after 209ms
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 2ms
[SEVERE] angular on lib/app_component.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
AngularParserException{NgParserWarningCode.ELEMENT_DECORATOR}
[INFO] Running build completed, took 53ms
[INFO] Caching finalized dependency graph completed, took 107ms
[SEVERE] Failed after 163ms
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 3ms
[SEVERE] angular on lib/app_component.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
AngularParserException{NgParserWarningCode.ELEMENT_DECORATOR}
[INFO] Running build completed, took 83ms
[INFO] Caching finalized dependency graph completed, took 118ms
[SEVERE] Failed after 205ms
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 2ms
[INFO] Running build completed, took 313ms
[INFO] Caching finalized dependency graph completed, took 101ms
[INFO] Succeeded after 422ms with 10 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 2ms
[INFO] Running build completed, took 441ms
[INFO] Caching finalized dependency graph completed, took 116ms
[INFO] Succeeded after 565ms with 8 outputs
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 2ms
[INFO] Running build completed, took 321ms
[INFO] Caching finalized dependency graph completed, took 83ms
[INFO] Succeeded after 411ms with 8 outputs
```

**Comment by leonsenft** [comment] 2018-04-21 14:49
Thanks for confirming.

**Closed by leonsenft** 2018-04-21 14:49 UTC
Labels: area: compiler, ☠️  release blocker, ⛳ state: needs info, ✉ dependency: build
