### ISSUE TITLE
can not build web project

### ISSUE THREAD

**Issue by zyzbroker** [dart-lang/angular#1411] opened 2018-06-15 03:00 UTC
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

Dart SDK :Dart VM version: 2.0.0-dev.63.0 (Unknown timestamp) on "linux_x64"
  angular: ^5.0.0-alpha+14
  angular_router: ^2.0.0-alpha+13
  angular_forms: ^2.0.0-alpha
OS: ubuntu 18.04
Browser: chrome
The build error is

[SEVERE] angular on package:angular_router/src/directives/router_link_active_directive.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
NoSuchMethodError: Class 'List<ConstructorElement>' has no instance method 'retype'.
Receiver: Instance(length:1) of '_GrowableList'
Tried calling: retype()
[SEVERE] angular on package:angular_router/src/directives/router_link_directive.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
NoSuchMethodError: Class 'List<ConstructorElement>' has no instance method 'retype'.
Receiver: Instance(length:1) of '_GrowableList'
Tried calling: retype()
[SEVERE] angular on package:angular_router/src/directives/router_outlet_directive.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
NoSuchMethodError: Class 'List<ConstructorElement>' has no instance method 'retype'.
Receiver: Instance(length:1) of '_GrowableList'
Tried calling: retype()
[SEVERE] angular on package:angular/src/common/directives/ng_class.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
NoSuchMethodError: Class 'List<ConstructorElement>' has no instance method 'retype'.
Receiver: Instance(length:1) of '_GrowableList'
Tried calling: retype()
[SEVERE] angular on package:angular/src/common/directives/ng_style.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
NoSuchMethodError: Class 'List<ConstructorElement>' has no instance method 'retype'.
Receiver: Instance(length:1) of '_GrowableList'
Tried calling: retype()
[SEVERE] angular on package:angular/src/common/directives/ng_for.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
NoSuchMethodError: Class 'List<ConstructorElement>' has no instance method 'retype'.
Receiver: Instance(length:1) of '_GrowableList'
Tried calling: retype()
[SEVERE] angular on package:angular/src/common/directives/ng_if.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
NoSuchMethodError: Class 'List<ConstructorElement>' has no instance method 'retype'.
Receiver: Instance(length:1) of '_GrowableList'
Tried calling: retype()
[SEVERE] angular on package:angular/src/common/directives/ng_switch.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
NoSuchMethodError: Class 'List<ConstructorElement>' has no instance method 'retype'.
Receiver: Instance(length:1) of '_GrowableList'
Tried calling: retype()
[SEVERE] angular on package:angular/src/common/directives/ng_template_outlet.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
NoSuchMethodError: Class 'List<ConstructorElement>' has no instance method 'retype'.
Receiver: Instance(length:1) of '_GrowableList'
Tried calling: retype()
[SEVERE] angular on lib/app_component.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
NoSuchMethodError: Class 'List<ConstructorElement>' has no instance method 'retype'.
Receiver: Instance(length:1) of '_GrowableList'
Tried calling: retype()
[SEVERE] angular on package:angular/src/security/safe_inner_html.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
NoSuchMethodError: Class 'List<ConstructorElement>' has no instance method 'retype'.
Receiver: Instance(length:1) of '_GrowableList'
Tried calling: retype()

**Comment by leonsenft** [comment] 2018-06-15 03:54
Duplicate of https://github.com/dart-lang/angular/issues/1406

**Closed by leonsenft** 2018-06-15 03:54 UTC
